FROM debian:bullseye
WORKDIR /builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt upgrade -y
RUN apt install -y git
#CMD [ "bash","#&& mv nodejs usr/local/bin/nodejs" ]

FROM node:18-bullseye
WORKDIR /builder
CMD ["npm", "start"]

FROM python:3.10.4-bullseye
COPY client-builder.py .
COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt
CMD ["python3", "client-builder.py"]