INSERT INTO "UnidadFormacion" VALUES
    ('AC1001', 'Lógica computacional', 1),
    ('AC1001B', 'Modelación de la física: Estática', 1),
    ('AC1002', 'Razonamiento matemático', 1),
    ('AC1002B', 'Modelación de la física: Dinámica', 1),
    ('AR1002B', 'Exploración en el hábitat: de la escala del elemento al territorio', 1),
    ('CV1009', 'Análisis químico del ambiente y de los materiales de construcción', 1),
    ('EG1001', 'Optativa de matemáticas y ciencias', 1),
    ('AR1025', 'Creatividad y diseño', 1),
    ('AR1026', 'Metodologías de investigación para proyectos de diseño', 1),
    ('AD1000B', 'El rol de los negocios en la sociedad', 1),
    ('AD1014', 'Dirección de los negocios', 1),
    ('CF1015', 'Análisis financiero', 1),
    ('EC1017', 'Economía empresarial', 1),
    ('FZ1011', 'Decisiones financieras', 1),
    ('MA1027', 'NI1001B', 1),
    ('Globalización de los negocios', 'RH1001B', 1),
    ('Estrategia y talento', 'TC1027', 1),
    ('Programación para negocios', 'F1001B', 1),
    ('Modelación de la ingeniería y ciencias', 'F1006B', 1),
    ('Modelación del movimiento en ingeniería', 'F1007B', 1),
    ('Aplicación de las leyes de conservación en sistemas ingenieriles', 'MA1028', 1),
    ('Modelación matemática fundamental', 'Q1019', 1),
    ('Análisis de la estructura, propiedades y transformación de la materia', 'TC1028', 1),
    ('Pensamiento computacional para ingeniería', 'EC1001B', 1),
    ('Transformación del México contemporáneo', 'MA1022', 1),
    ('Pensamiento matemático I', 'P1010', 1),
    ('Filosofía política para los dilemas contemporáneos', 'P1011', 1),
    ('Introducción a las ciencias sociales', 'RI1001B', 1),
    ('Desafíos globales', 'TC1001B', 1),
    ('Principios de programación para las ciencias sociales', 'A1004', 1),
    ('Cultura visual y sonora', 'AV1002B', 1),
    ('Técnicas y discursos fotográficos', 'CO1001B', 1),
    ('Metodologías de investigación de factores humanos', 'DL1022', 1),
    ('Metodologías del pensamiento creativo', 'EH1001B', 1),
    ('Inmersión y experimentación creativa', 'F1002B', 1),
    ('Modelación del movimiento en bioingeniería y procesos químicos', 'F1003B', 1),
    ('Aplicación de las leyes de conservación en ingeniería de procesos', 'Q1028', 1),
    ('Fundamentación de la estructura y transformación de la materia', 'Q1029', 1),
    ('Análisis de la estructura y transformación de la materia', 'F1008B', 1),
    ('Modelación del movimiento en ciencias', 'F1009B', 1),
    ('Aplicación de las leyes de conservación en ciencias', 'F1004B', 1),
    ('Modelación computacional del movimiento', 'F1005B', 1),
    ('Modelación computacional aplicando leyes de conservación', 'TC1033', 1),
    ('Pensamiento computacional orientado a objetos', 'Q1020', 1),
    ('Análisis de la estructura y propiedades de la materia', 'TC1029', 1),
    ('Pensamiento computacional y programación', 'AR1003B', 1),
    ('Modelación de la física en el ambiente construido', 'CV1007', 1),
    ('Razonamiento basado en matemáticas', 'CV1008', 1),
    ('Resolución de problemas con lógica computacional', 'Segundo Semestre', 1),
    ('AC1003', 'Análisis con Probabilidad y Estadística', 1),
    ('AC1003B', 'Sistemas constructivos', 1),
    ('AC1004B', 'Información espacial', 1),
    ('AC1005B', 'Sistemas de información geográfica', 1),
    ('CV1010', 'Fundamentos de geología aplicada al ambiente construido', 1),
    ('CV1011', 'Evaluación del impacto ambiental de proyectos territoriales', 1),
    ('CV1012', 'Aplicación de métodos numéricos al ambiente construido', 1),
    ('EG1002', 'Optativa de humanidades y bellas artes', 1),
    ('AR1027', 'Métodos de diseño', 1),
    ('AR1028', 'Técnicas de representación espacial y de imagen', 1),
    ('AD1016', 'Comunicación que inspira', 1),
    ('CD1004', 'Análisis para la toma de decisiones', 1),
    ('CD1005', 'Pensamiento estadístico', 1),
    ('CF1001B', 'Dirección financiera', 1),
    ('D1029', 'Legalidad y negocios responsables', 1),
    ('EM1001B', 'Ideación y prototipado', 1),
    ('EM1009', 'Innovación de modelos de negocios', 1),
    ('MT1001B', 'Descubrimientos del mercado para el desarrollo de estrategias', 1),
    ('RH1004', 'Procesos de gestión de talento', 1),
    ('F1008', 'Experimentación física y pensamiento estadístico', 1),
    ('F1015B', 'Aplicación de la termodinámica en sistemas ingenieriles', 1),
    ('F1016B', 'Análisis de sistemas eléctricos en sistemas ingenieriles', 1),
    ('F1017B', 'Análisis de sistemas electromagnéticos en sistemas ingenieriles', 1),
    ('MA1029', 'Modelación matemática intermedia', 1),
    ('MA1030', 'Modelación matricial', 1),
    ('MA1031', 'Análisis estadístico', 1),
    ('Q1021', 'Experimentación química y pensamiento estadístico fundamental', 1),
    ('D1001B', 'Introducción al derecho', 1),
    ('EC1002B', 'Emprendimiento y tecnología para la transformación de México', 1),
    ('EC1013', 'Macroeconomía', 1),
    ('EC1014', 'Microeconomía', 1),
    ('MA1023', 'Métodos cuantitativos I', 1),
    ('MA1024', 'Pensamiento matemático II', 1),
    ('TC1002B', 'Herramientas tecnológicas para las ciencias sociales', 1),
    ('AR1001B', 'Representación formal del espacio', 1),
    ('AV1001B', 'Narrativa audiovisual', 1),
    ('EH1008', 'Imaginarios culturales de México', 1),
    ('EH1009', 'Semiótica y narratologías contemporáneas', 1),
    ('H1001B', 'Estructuras simbólicas en la imagen, la literatura y la música', 1),
    ('F1010B', 'Aplicación de la termodinámica en ingeniería de procesos', 1),
    ('F1011B', 'Análisis de sistemas eléctricos en ingeniería de procesos', 1),
    ('F1012B', 'Análisis de sistemas electromagnéticos en ingeniería de procesos', 1),
    ('Q1022', 'Análisis de la transformación de la materia en procesos químicos', 1),
    ('Q1023', 'Experimentación química y pensamiento estadístico intermedio', 1),
    ('F1018B', 'Aplicación de la termodinámica en ciencias', 1),
    ('F1019B', 'Análisis de sistemas eléctricos en ciencias', 1),
    ('F1020B', 'Análisis de sistemas electromagnéticos en ciencias', 1),
    ('BT1013', 'Análisis de biología computacional', 1),
    ('F1013B', 'Modelación computacional de sistemas eléctricos', 1),
    ('F1014B', 'Modelación computacional de sistemas electromagnéticos', 1),
    ('TC1003B', 'Modelación de la ingeniería con matemática computacional', 1),
    ('TC1030', 'Programación orientada a objetos', 1),
    ('OP1007', 'Optativa de fundamentos en ingeniería', 1),
    ('AR1004B', 'Modelación y representación gráfica de un edificio', 1),
    ('AR1005B', 'Modelación y representación gráfica de tu campus con topografía', 1),
    ('AR1006B', 'Modelación y representación gráfica de tu entorno con geomática', 1),
    ('CV1013', 'Análisis de fenómenos naturales y sociales con probabilidad y estadística', 1),
    ('AR2002B', 'Diseño y construcción de un hábitat efímero', 3),
    ('AR2035', 'La conceptualización del espacio, su teoría y su historia', 3),
    ('AR2036', 'Representación de la arquitectura y su construcción', 3),
    ('EG1003', 'Optativa de ciencias sociales y del comportamiento', 3),
    ('VA1001B', 'Tópico de exploración', 3),
    ('AD1001B', 'Creación de valor compartido', 3),
    ('CF1016', 'Estrategias de planeación financiera', 3),
    ('EM1010', 'Proyecto de innovación empresarial', 3),
    ('FZ1012', 'Evaluación de proyectos de inversión', 3),
    ('MT1002B', 'Construcción de soluciones para el mercado', 3),
    ('MT1011', 'Estrategias de mercado y diferenciación', 3),
    ('NI1004', 'Competitividad internacional  y oportunidades de crecimiento', 3),
    ('RH1005', 'Dimensión estratégica del capital humano', 3),
    ('IN1001B', 'Diseño y análisis de experimentos para la innovación ingenieril', 3),
    ('IN1002B', 'Desarrollo de proyectos de análisis de datos', 3),
    ('M1011', 'Análisis de equilibrio estático', 3),
    ('MA1034', 'Modelación de procesos mediante algebra lineal', 3),
    ('MA1035', 'Modelación en ingeniería mediante sistemas dinámicos', 3),
    ('TE1020', 'Análisis de circuitos eléctricos', 3),
    ('EC1003B', 'Macroeconomía y desarrollo económico', 3),
    ('EC1015', 'Economía conductual', 3),
    ('EC1016', 'Economía para la toma de decisiones', 3),
    ('MA1025', 'Métodos cuantitativos II', 3),
    ('MA1026', 'Pensamiento matemático III', 3),
    ('P1001B', 'Participación política y sociología de la identidad', 3),
    ('BT1014', 'Fundamentación de la biología molecular', 3),
    ('IQ1001B', 'Aplicación de la conservación de la materia en ingeniería de procesos', 3),
    ('IQ1002B', 'Aplicación de la conservación de la energía en ingeniería de procesos', 3),
    ('Q1024', 'Aplicación del análisis químico', 3),
    ('Q1025', 'Experimentación en química analítica', 3),
    ('Q1026', 'Análisis estructural de moléculas orgánicas y sus propiedades', 3),
    ('Q1027', 'Fundamentación de la estructura y propiedades de biomoléculas', 3),
    ('F1009', 'Análisis de métodos matemáticos para la física', 3),
    ('F1010', 'Modelación con ecuaciones diferenciales', 3),
    ('MA1001B', 'Modelación estadística para la toma de decisiones', 3),
    ('MA1002B', 'Modelación de sistemas con ecuaciones diferenciales', 3),
    ('MA1036', 'Fundamentación del álgebra lineal', 3),
    ('MA1033', 'Análisis de ecuaciones diferenciales', 3),
    ('TC1004B', 'Implementación de internet de las cosas', 3),
    ('TC1031', 'Programación de estructuras de datos y algoritmos fundamentales', 3),
    ('TC1032', 'Modelación de sistemas mínimos y arquitecturas computacionales', 3),
    ('TI1015', 'Análisis de requerimientos de software', 3),
    ('DS1008', 'Evaluación del capital natural y principios de sustentabilidad', 3),
    ('SD1001', 'Sistema musculoesquelético', 3),
    ('SD1002B', 'Metabolismo y energía', 3),
    ('SD1003', 'Aporte y consumo de oxígeno', 3),
    ('Q1001B', 'Fundamentación de las propiedades de nanomateriales y materiales', 3),
    ('Q1002B', 'Obtención de nanomateriales, materiales orgánicos y bioinorgánicos', 3),
    ('TE1019', 'Fundamentación de ingeniería eléctrica y electrónica', 3),
    ('A2001B', 'Pre-producción de cortometraje animado', 3),
    ('A2002B', 'Producción de cortometraje animado', 3),
    ('A2012', 'Dibujo', 3),
    ('A2013', 'Historia de la animación', 3),
    ('A2014', 'Fundamentos de la animación', 3),
    ('AV2001B', 'Producción de audio, video y diseño digital', 3),
    ('CO2001B', 'Metodologías de investigación para la comunicación', 3),
    ('CO2011', 'Teorías de la comunicación', 3),
    ('EH2006', 'Del humanismo al post-humanismo', 3),
    ('DL2001B', 'Comunicación digital del producto', 3),
    ('DL2002B', 'Configuración del objeto', 3),
    ('DL2042', 'Representación visual', 3),
    ('DL2043', 'Materia y expresión', 3),
    ('D2001B', 'Bienes y derechos reales', 3),
    ('D2002B', 'Derecho constitucional', 3),
    ('D2031', 'Argumentación jurídica', 3),
    ('D2032', 'Personas y acto jurídico', 3),
    ('D2033', 'Seminario de argumentación jurídica', 3),
    ('D2034', 'Seminario de personas y acto jurídico', 3),
    ('D2035', 'Seminario de teoría del derecho', 3),
    ('D2036', 'Teoría del derecho', 3),
    ('ED2001', 'Fundamentos de la pedagogía', 3),
    ('ED2001B', 'Análisis de problemáticas educativas', 3),
    ('ED2002', 'Metodologías de la investigación educativa', 3),
    ('ED2002B', 'Fundamentación pedagógica aplicada a las soluciones de aprendizaje', 3),
    ('H2001B', 'Análisis del discurso', 3),
    ('H2002B', 'Textos clásicos', 3),
    ('H2050', 'Análisis crítico de textos', 3),
    ('H2051', 'Estructuras y análisis del español', 3),
    ('MI2001B', 'Metodologías de la investigación periodística', 3),
    ('SO2001', 'Estudios sociales y políticos', 3),
    ('F2010B', 'Fundamentos de la acústica', 3),
    ('TM2001', 'Teoría y estilos musicales', 3),
    ('TM2001B', 'Entrenamiento auditivo e instrumental', 3),
    ('TM2002', 'Negocios en la industria de la música', 3),
    ('AR2001B', 'Diagnóstico territorial', 3),
    ('AR2003B', 'Ecobarrio', 3),
    ('AR2037', 'Derecho Urbano', 3),
    ('BT2027', 'Ecología urbana', 3),
    ('CV2041', 'Infraestructura urbana', 3),
    ('AR2004B', 'Arquitectura y contextos', 4),
    ('AR2007B', 'Equipamiento comunitario', 4),
    ('AR2039', 'Investigación y proyecto arquitectónico', 4),
    ('EG1004', 'Optativa de liderazgo, emprendimiento e innovación', 4),
    ('NI2001B', 'Panorama internacional de los negocios', 4),
    ('NI2002B', 'Plan de exportación', 4),
    ('NI2026', 'Negocios globales: tendencias y detección de riesgos', 4),
    ('NI2027', 'Operación logística internacional', 4),
    ('IN2001B', 'Desarrollo de proyectos con visión sistémica', 4),
    ('IN2002B', 'Mejora de un proceso organizacional con métodos estadísticos', 4),
    ('IN2003B', 'Conceptualización de procesos con enfoque innovador', 4),
    ('IN2032', 'Análisis estadístico de datos', 4),
    ('IN2037', 'Diseño de sistemas ciberfísicos', 4),
    ('IN2038', 'Evaluación económica de proyectos', 4),
    ('M2001B', 'Análisis de materiales y manufactura', 4),
    ('M2005', 'Análisis  de mecanismos', 4),
    ('MR2003B', 'Integración mecatrónica', 4),
    ('MR2004B', 'Implementación de sistemas mecatrónicos', 4),
    ('MR2022', 'Análisis de elementos de la mecatrónica', 4),
    ('MR2023', 'Modelación y automatización', 4),
    ('AG2001B', 'Análisis de biosistemas productivos', 4),
    ('AG2002B', 'Evaluación de nutrición y sanidad en los biosistemas', 4),
    ('AG2029', 'Fundamentación de biosistemas productivos', 4),
    ('AG2030', 'Integración de procesos bioproductivos', 4),
    ('DS2001B', 'Conservación de recursos naturales en biosistemas', 4),
    ('IN2033', 'Gestión de biosistemas productivos', 4),
    ('TA2001B', 'Diseño de alimentos saludables', 4),
    ('TA2002B', 'Planeación de sistemas de distribución de alimentos', 4),
    ('TA2003B', 'Evaluación de factibilidad de nuevos productos', 4),
    ('TA2017', 'Diseño sustentable en procesamiento de alimentos', 4),
    ('TA2018', 'Optimización de procesos y sistemas de inocuidad', 4),
    ('TA2019', 'Análisis fisicoquímico en el diseño de alimentos', 4),
    ('BT2002B', 'Elaboración de productos biotecnológicos', 4),
    ('BT2003B', 'Síntesis de biofábricas', 4),
    ('BT2019', 'Análisis y estudio de biosistemas', 4),
    ('BT2020', 'Aplicación de bases moleculares', 4),
    ('CV2001B', 'Análisis de la interacción del ambiente construido y el entorno', 4),
    ('CV2002B', 'Evaluación del comportamiento de materiales en estructuras', 4),
    ('CV2003B', 'Análisis del comportamiento de sistemas hidráulicos', 4),
    ('CV2035', 'Modelación de la información en la construcción', 4),
    ('CV2036', 'Gestión de costos', 4),
    ('CV2037', 'Planeación y control de obra', 4),
    ('MA2001B', 'Optimización determinista', 4),
    ('MA2002B', 'Análisis de criptografía y seguridad', 4),
    ('TC2004B', 'Análisis de ciencia de datos', 4),
    ('TC2032', 'Diseño de agentes inteligentes', 4),
    ('TC2033', 'Análisis de sistemas basados en conocimiento', 4),
    ('TC2034', 'Modelación del aprendizaje con inteligencia artificial', 4),
    ('DS2002B', 'Implementación de programas de manejo de recursos', 4),
    ('IQ2001B', 'Integración de procesos energéticos', 4),
    ('IQ2002B', 'Dimensionamiento de procesos energéticos', 4),
    ('IQ2009', 'Análisis termodinámico de procesos energéticos', 4),
    ('IQ2010', 'Diseño de procesos para el transporte de fluidos', 4),
    ('IQ2011', 'Diseño de procesos de transferencia de calor', 4),
    ('TE2005B', 'Aplicación de la teoría electromagnética', 4),
    ('TE2006B', 'Evaluación de circuitos eléctricos', 4),
    ('TE2007B', 'Aplicación de dispositivos electrónicos', 4),
    ('TE2047', 'Análisis de circuitos eléctricos de corriente alterna', 4),
    ('TE2048', 'Análisis de sistemas lógicos y circuitos digitales', 4),
    ('TE2049', 'Fundamentación de la física de estado sólido y optoelectrónica', 4),
    ('F2002B', 'Solución de problemas de mecánica clásica', 4),
    ('F2003B', 'Modelación numérica de sistemas físicos determinísticos', 4),
    ('F2004B', 'Aplicación de las fuentes alternas de energía', 4),
    ('F2017', 'Fundamentación de la electrodinámica', 4),
    ('NN2001B', 'Diseño y creación de soluciones innovadoras', 4),
    ('NN2007', 'Estudio de metodologías para la innovación', 4),
    ('OP2019', 'Optativa de acentuación en ingeniería I', 4),
    ('OP2026', 'Optativa de acentuación en ingeniería II', 4),
    ('BI2001B', 'Diseño de sistemas de bioinstrumentación analógica', 4),
    ('BI2002B', 'Diseño de sistemas de bioinstrumentación digital', 4),
    ('BI2003B', 'Análisis químico, biológico y molecular', 4),
    ('BI2010', 'Análisis de señales y sistemas biomédicos', 4),
    ('BI2011', 'Aplicación de tecnologías de la información en salud', 4),
    ('M2002B', 'Diseño de productos sometidos a cargas estáticas', 4),
    ('M2003B', 'Diseño dinámico', 4),
    ('M2033', 'Análisis de esfuerzos y deformaciones', 4),
    ('M2034', 'Análisis del movimiento de cuerpos rígidos', 4),
    ('M2035', 'Fundamentación de ingeniería de materiales', 4),
    ('NT2001B', 'Fabricación de nanoestructuras por métodos químicos', 4),
    ('NT2002B', 'Fabricación de nano y microestructuras por métodos físicos', 4),
    ('Q2001B', 'Fundamentación fisicoquímica de las propiedades de las nanoestructuras', 4),
    ('Q2024', 'Caracterización de materiales y nanomateriales', 4),
    ('Q2025', 'Fundamentación de química médica y nanomedicina', 4),
    ('IQ2007B', 'Diseño de sistemas de flujo de fluidos', 4),
    ('IQ2008B', 'Diseño de sistemas de transferencia de calor', 4),
    ('IQ2009B', 'Análisis de procesos de transferencia de calor y flujo de fluidos', 4),
    ('IQ2015', 'Modelación de fenómenos de transporte', 4),
    ('MA2016', 'Modelación matemática avanzada', 4),
    ('TE2002B', 'Diseño con lógica programable', 4),
    ('TE2003B', 'Diseño de sistemas en chip', 4),
    ('TE2044', 'Fundamentación electrónica', 4),
    ('TE2045', 'Diseño de circuitos electrónicos', 4),
    ('TC2005B', 'Construcción de software y toma de decisiones', 4),
    ('TC2006B', 'Interconexión de dispositivos', 4),
    ('TC2037', 'Implementación de métodos computacionales', 4),
    ('AD2029', 'Modelación, estructura y operación de los negocios', 4),
    ('TI2002B', 'Evaluación de arquitecturas empresariales', 4),
    ('TI2003B', 'Evaluación de tecnología para los negocios', 4),
    ('TI2004B', 'Exploración e interpretación de datos', 4),
    ('TI2018', 'Diseño de arquitecturas, uso y administración de datos', 4),
    ('TI2019', 'Evaluación y administración de proyectos', 4),
    ('A2003B', 'Arte conceptual', 4),
    ('A2004B', 'Fundamentos de interacción', 4),
    ('A2005B', 'Arte instalación', 4),
    ('A2015', 'Exploración de la forma', 4),
    ('A2016', 'Introducción al 3D', 4),
    ('AD2001B', 'Detección de oportunidades estratégicas', 4),
    ('AD2002B', 'Diseño de organizaciones flexibles', 4),
    ('AD2004B', 'Liderazgo para la transformación', 4),
    ('AD2025', 'Pensamiento estratégico', 4),
    ('FZ2001B', 'Análisis de inversiones', 4),
    ('FZ2002B', 'Cultura financiera', 4),
    ('FZ2004B', 'Gestión de tesorería', 4),
    ('FZ2019', 'Modelos econométricos', 4),
    ('FZ2020', 'Series de tiempo', 4),
    ('FZ2021', 'Teoría de inversiones', 4),
    ('CF2001B', 'Diagnóstico financiero', 4),
    ('CF2002B', 'Integración financiera de procesos de negocio', 4),
    ('CF2022', 'Cumplimiento fiscal', 4),
    ('CF2023', 'Optimización de costos', 4),
    ('FZ2003B', 'Decisiones de negocio estratégicas', 4),
    ('TI2016', 'Estructuras de información', 4),
    ('AV2002B', 'Guionismo y producción de narrativas audiovisuales', 4),
    ('AV2016', 'Fotografía publicitaria y comercial', 4),
    ('CR2001B', 'Comunicación estratégica aplicada', 4),
    ('EM2001B', 'Adaptación de oportunidad y solución', 4),
    ('EM2002B', 'Evaluación y comunicación de oportunidades', 4),
    ('EM2003B', 'Exploración de alto impacto', 4),
    ('EM2013', 'Innovación en la cadena de valor', 4),
    ('EM2014', 'Liderazgo emprendedor', 4),
    ('EM2015', 'Oportunidades de emprendimiento corporativo', 4),
    ('DL2003B', 'Pensamiento y proceso creativo', 4),
    ('DL2004B', 'Especificación de productos y servicios', 4),
    ('DL2005B', 'Diseño e innovación', 4),
    ('DL2044', 'Administración de proyectos de diseño', 4),
    ('RH2001B', 'Estrategias para potenciar el talento humano', 4),
    ('RH2002B', 'Planeación del capital humano', 4),
    ('RH2003B', 'Valoración estratégica del trabajo', 4),
    ('RH2012', 'Atracción y desarrollo del talento en entornos digitales', 4),
    ('RH2013', 'Desempeño y retribución en contextos globales', 4),
    ('TI2015', 'Analítica del talento', 4),
    ('EC2001B', 'Dinero y capitales', 4),
    ('EC2003B', 'Incentivos del consumidor y productor', 4),
    ('EC2004B', 'Origen y futuro del panorama macroeconómico', 4),
    ('EC2029', 'Fundamentos de econometría', 4),
    ('MA2012', 'Fundamentos de estadística', 4),
    ('MA2013', 'Pensamiento matemático IV', 4),
    ('D2003B', 'Derecho penal y delitos en especial', 4),
    ('D2004B', 'Derechos humanos y su interpretación judicial', 4),
    ('D2005B', 'Solución de conflictos y teoría general del proceso', 4),
    ('D2037', 'Derecho de las obligaciones I', 4),
    ('D2038', 'Derecho de las obligaciones II', 4),
    ('D2039', 'Seminario de derecho de las obligaciones I', 4),
    ('ED2003', 'Introducción a la administración educativa', 4),
    ('ED2003B', 'Desarrollo de proyectos educativos basados en tecnología', 4),
    ('ED2004B', 'Exploración de tendencias tecnológicas en educación', 4),
    ('ED2005B', 'Uso de tecnología en la investigación educativa', 4),
    ('MT2001B', 'Inteligencia de mercado para la generación de conocimiento del consumidor', 4),
    ('MT2002B', 'Inteligencia exploratoria de mercados', 4),
    ('MT2003B', 'Segmentación y posicionamiento de estrategias de valor', 4),
    ('MT2027', 'Definición competitiva de mercado', 4),
    ('MT2028', 'Diseño de métricas de mercadotecnia', 4),
    ('MT2029', 'Visión holística del consumidor', 4),
    ('AD2003B', 'Indicadores y riesgos con visión estratégica', 4),
    ('CD2001B', 'Diagnóstico para líneas de acción', 4),
    ('CD2008', 'Análisis descriptivo', 4),
    ('CD2009', 'Manipulación de datos', 4),
    ('TI2017', 'Integración de base de datos', 4),
    ('H2003B', 'Literatura de los Siglos de Oro', 4),
    ('H2004B', 'Literatura española medieval', 4),
    ('H2005B', 'Literatura novohispana', 4),
    ('H2052', 'Teoría literaria', 4),
    ('MI2002B', 'Producción de contenidos noticiosos', 4),
    ('MI2007', 'Ejercicio periodístico, derecho a la información y opinión pública', 4),
    ('RI2001B', 'Análisis histórico del sistema internacional', 4),
    ('RI2002B', 'Escenarios regionales en el mundo contemporáneo', 4),
    ('RI2003B', 'Prospectiva sobre escenarios político-económicos internacionales', 4),
    ('RI2039', 'Teorías clásicas de relaciones internacionales', 4),
    ('RI2040', 'Teorías contemporáneas de relaciones internacionales', 4),
    ('TM2002B', 'Aplicación de tecnología en la producción sonora', 4),
    ('TM2003', 'Producción sonora y mezcla digital', 4),
    ('TM2003B', 'Técnicas de grabación sonora', 4),
    ('TM2004B', 'Proyecto de producción musical', 4),
    ('P2001B', 'Opinión pública', 4),
    ('P2002B', 'Instituciones, regulación y política pública', 4),
    ('TC2001B', 'Ciencia de datos para la toma de decisiones I', 4),
    ('TC3066', 'Métodos econométricos y política pública', 4),
    ('AR2005B', 'Ciudades competitivas: Innovación', 4),
    ('AR2006B', 'Ciudades competitivas: Movilidad', 4),
    ('AR2010B', 'Ciudades competitivas: Calidad de vida', 4),
    ('AR2038', 'Ciudades del futuro', 4),
    ('AR2008B', 'Vivienda colectiva', 5),
    ('AR2009B', 'Vivienda unifamiliar', 5),
    ('AR2040', 'Constructibilidad', 5),
    ('EG1005', 'Optativa de ética y ciudadanía', 5),
    ('NI2003B', 'Administración de importaciones y sus regulaciones', 5),
    ('NI2004B', 'Desarrollo internacional de servicios', 5),
    ('NI2025', 'Negociación Intercultural', 5),
    ('NI2028', 'Ventas y contratos internacionales', 5),
    ('IN2004B', 'Generación de valor con analítica de datos', 5),
    ('IN2005B', 'Evaluación de la competitividad organizacional', 5),
    ('IN2006B', 'Análisis de la viabilidad de proyectos con perspectiva sistémica', 5),
    ('IN2039', 'Visualización de datos para la toma de decisiones', 5),
    ('IN2040', 'Optimización de procesos organizacionales', 5),
    ('IN2041', 'Mejora de procesos con métodos heurísticos y metaheurísticos', 5),
    ('MR2005B', 'Solución de problemas de procesos', 5),
    ('MR2006B', 'Automatización industrial', 5),
    ('MR2024', 'Diseño mecatrónico', 5),
    ('MR2025', 'Diseño de sistemas de control', 5),
    ('AG2003B', 'Integración de tecnologías sustentables en biosistemas', 5),
    ('BT2001B', 'Mejora de biosistemas con genética y biotecnología', 5),
    ('IN2034', 'Evaluación de la productividad', 5),
    ('IN2035', 'Gestión avanzada de la producción', 5),
    ('IN2036', 'Aplicación de metrología en biosistemas productivos', 5),
    ('MR2001B', 'Aplicación de automatización y control en biosistemas', 5),
    ('TA2004B', 'Diseño de procesos sustentables', 5),
    ('TA2005B', 'Análisis del consumidor y mercado de alimentos', 5),
    ('TA2006B', 'Diseño de sistemas de administración de procesos e inocuidad', 5),
    ('TA2020', 'Administración de procesos y sistemas de inocuidad', 5),
    ('TA2021', 'Aplicación del análisis sensorial en alimentos', 5),
    ('TA2022', 'Simulación de procesos de transformación de alimentos', 5),
    ('BT2004B', 'Experimentación in vitro', 5),
    ('BT2005B', 'Integración de operaciones de transferencia', 5),
    ('BT2026', 'Análisis de fenómenos de transporte', 5),
    ('CV2004B', 'Evaluación del comportamiento de sistemas estructurales', 5),
    ('CV2005B', 'Diseño de sistemas hidráulicos para el uso sustentable del agua', 5),
    ('CV2006B', 'Diseño de vialidades para el desarrollo', 5),
    ('CV2038', 'Gestión de proyectos', 5),
    ('CV2039', 'Gestión de operaciones de construcción', 5),
    ('CV2040', 'Gestión empresarial en la industria de la construcción', 5),
    ('MA2003B', 'Aplicación de métodos multivariados en ciencia de datos', 5),
    ('MA2004B', 'Optimización estocástica', 5),
    ('MA2005B', 'Aplicación de criptografía y seguridad', 5),
    ('MA2014', 'Análisis de métodos de razonamiento e incertidumbre', 5),
    ('MA2015', 'Diseño de algoritmos matemáticos bioinspirados', 5),
    ('TC2035', 'Diseño de redes neuronales y aprendizaje profundo', 5),
    ('IQ2003B', 'Evaluación de procesos energéticos', 5),
    ('IQ2004B', 'Evaluación del desempeño energético de procesos industriales', 5),
    ('IQ2012', 'Aplicación de los principios de eficiencia energética', 5),
    ('IQ2013', 'Análisis de procesos y economía circular', 5),
    ('TC2009B', 'Diseño usando microcontroladores y arquitectura computacional', 5),
    ('TC2039', 'Desarrollo de sistemas digitales', 5),
    ('TE2008B', 'Evaluación de Dispositivos Electrónicos', 5),
    ('TE2009B', 'Análisis de sistemas y dispositivos electrónicos de control', 5),
    ('TE2046', 'Análisis de señales y sistemas', 5),
    ('TE2050', 'F2005B', 5),
    ('Análisis de fenómenos ópticos', 'F2006B', 5),
    ('Modelación numérica de sistemas estocásticos', 'F2007B', 5),
    ('Análisis de los sistemas termodinámicos y estadísticos', 'F2018', 5),
    ('Análisis de sistemas cuánticos', 'NN2002B', 5),
    ('Diseño y evaluación de emprendimientos tecnológicos', 'NN2008', 5),
    ('Análisis de factibilidad y viabilidad de proyectos de innovación', 'OP2027', 5),
    ('Optativa de acentuación en ingeniería III', 'OP2028', 5),
    ('Optativa de acentuación en ingeniería IV', 'BI2004B', 5),
    ('Análisis y diseño en biomecánica', 'BI2005B', 5),
    ('Aplicación de bioinstrumentación y tecnologías biomédicas', 'BI2006B', 5),
    ('Gestión y validación de tecnologías biomédicas', 'BI2012', 5),
    ('Caracterización de biomateriales', 'BI2013', 5),
    ('Modelación y control de sistemas biomédicos', 'SD1012', 5),
    ('Sistema nervioso', 'M2004B', 5),
    ('Diseño de mecanismos', 'M2005B', 5),
    ('Diseño de sistemas termofluídicos', 'M2036', 5),
    ('Fundamentación de mecánica de fluidos', 'M2037', 5),
    ('Análisis de los procesos de transformación energética', 'M2038', 5),
    ('Modelación de transferencia de calor', 'F2001B', 5),
    ('Desarrollo de nanosistemas fotónicos', 'F2015', 5),
    ('Fundamentación del estado sólido de la materia', 'F2016', 5),
    ('Fundamentación de electromagnetismo', 'NT2003B', 5),
    ('Desarrollo de nanosistemas fluídicos y mecánicos', 'Q2002B', 5),
    ('Modelación de sistemas moleculares', 'Q2026', 5),
    ('Formulación de productos nanotecnológicos', 'IQ2010B', 5),
    ('Diseño de procesos de separación', 'IQ2011B', 5),
    ('Diseño de reactores químicos', 'IQ2012B', 5),
    ('Análisis de procesos de separación y reacción', 'IQ2016', 5),
    ('Predicción del equilibrio químico y de fases', 'MR2002B', 5),
    ('Análisis de sistemas de control', 'TC2036', 5),
    ('Implementación de redes seguras', 'TE2004B', 5),
    ('Diseño de sistemas embebidos avanzados', 'TC2007B', 5),
    ('Integración de seguridad informática en redes y sistemas de software', 'TC2008B', 5),
    ('Modelación de sistemas multiagentes con gráficas computacionales', 'TC2038', 5),
    ('Análisis y diseño de algoritmos avanzados', 'AD2008B', 5),
    ('Administración del cambio', 'AD2030', 5),
    ('Análisis del comportamiento y desempeño organizacional', 'FZ2025', 5),
    ('Análisis de las actividades económicas', 'TI2005B', 5),
    ('Diseño de procesos y arquitecturas empresariales', 'TI2006B', 5),
    ('Soporte analítico para la toma de decisiones', 'TI2020', 5),
    ('Implementación de tecnología en los procesos', 'OP3070', 5),
    ('Optativa de arte digital I', 'OP3071', 5),
    ('Optativa de arte digital II', 'OP3072', 5),
    ('Optativa de arte digital III', 'OP3073', 5),
    ('Optativa de arte digital IV', 'OP3074', 5),
    ('Optativa de arte digital V', 'OP3075', 5),
    ('Optativa de arte digital VI', 'AD2005B', 5),
    ('Aseguramiento de la co-creación de valor', 'AD2006B', 5),
    ('Diseño estratégico para crear valor', 'AD2026', 5),
    ('Construcción de habilidades interpersonales', 'AD2027', 5),
    ('Innovación y co-creación de valor', 'FZ2005B', 5),
    ('Análisis de financiamiento', 'FZ2008B', 5),
    ('Valuación de empresas', 'FZ2009B', 5),
    ('Vehículos de inversión y cobertura', 'FZ2022', 5),
    ('Algoritmos y análisis de datos', 'FZ2023', 5),
    ('Instrumentos derivados', 'FZ2024', 5),
    ('Modelación y programación financiera', 'CF2003B', 5),
    ('Desarrollo de arquitectura contable', 'CF2024', 5),
    ('Diseño de estrategia financiera', 'CF2025', 5),
    ('Valuación y presentación de financiamientos', 'CF2026', 5),
    ('Valuación y presentación de inversiones', 'FZ2006B', 5),
    ('Análisis fundamental de empresas', 'FZ2007B', 5),
    ('Creación de valor corporativo', 'AV2003B', 5),
    ('Narrativa documental', 'CO2002B', 5),
    ('Comunicación, mercadotecnia digital y minería de datos', 'CO2012', 5),
    ('Estudios culturales y medios', 'MI2003B', 5),
    ('Producción periodística convergente', 'EM2004B', 5),
    ('Diseño de prototipos', 'EM2005B', 5),
    ('Diseño de soluciones de alto impacto', 'EM2006B', 5),
    ('Generación y validación de prototipos', 'EM2016', 5),
    ('Metodologías de innovación', 'EM2017', 5),
    ('Metodologías de innovación tecnológica', 'EM2018', 5),
    ('Técnicas de prototipaje', 'OP3076', 5),
    ('Optativa de diseño I', 'OP3077', 5),
    ('Optativa de diseño II', 'OP3078', 5),
    ('Optativa de diseño III', 'OP3079', 5),
    ('Optativa de diseño IV', 'OP3080', 5),
    ('Optativa de diseño V', 'OP3081', 5),
    ('Optativa de diseño VI', 'AD2028', 5),
    ('Responsabilidad social y talento humano', 'RH2004B', 5),
    ('Comprensión del ambiente laboral', 'RH2005B', 5),
    ('Creación de valor desde el talento', 'RH2006B', 5),
    ('Diseño de experiencias laborales plenas', 'RH2014', 5),
    ('Organizaciones positivas', 'RH2015', 5),
    ('Versatilidad organizacional', 'EC2005B', 5),
    ('Competencia económica', 'EC2006B', 5),
    ('Decisiones estratégicas en mercados e instituciones', 'EC2007B', 5),
    ('Dinámica del crecimiento nacional y regional', 'EC2030', 5),
    ('Econometría I', 'EC2031', 5),
    ('Econometría II', 'EC2032', 5),
    ('Multivariante', 'D2006B', 5),
    ('Contratos civiles y mercantiles', 'D2007B', 5),
    ('Derecho administrativo I', 'D2008B', 5),
    ('Familia y sucesiones', 'D2040', 5),
    ('Derecho laboral I', 'D2041', 5),
    ('Derecho laboral ll', 'D2042', 5),
    ('Seminario de derecho de las obligaciones II', 'ED2004', 5),
    ('Educación global y comparada', 'ED2006B', 5),
    ('Diseño de soluciones para retos educativos', 'ED2007B', 5),
    ('Desarrollo de proyectos en el marco de las políticas educativas vigentes', 'MT2004B', 5),
    ('Desarrollo de marcas que transforman', 'MT2005B', 5),
    ('Diseño de experiencias omnicanal', 'MT2006B', 5),
    ('Gestión sustentable de proyectos de mercadotecnia', 'MT2030', 5),
    ('Diseño de estrategias de mercadotecnia interna', 'MT2031', 5),
    ('Optimización de precios y cadenas de valor', 'AD2007B', 5),
    ('Líneas de acción estratégicas', 'CD2010', 5),
    ('Introducción a la econometría', 'CD2011', 5),
    ('Minería de datos', 'TC2003B', 5),
    ('Gestión de proyectos de plataformas tecnológicas', 'TI2001B', 5),
    ('Plataformas de analítica de negocios para organizaciones', 'H2006B', 5),
    ('Narrativa Iberoamericana de los siglos XIX y XX', 'H2007B', 5),
    ('Poesía Iberoamericana de los siglos XIX y XX', 'H2008B', 5),
    ('Teatro y ensayo iberoamericanos de los siglos XIX y XX', 'H2053', 5),
    ('Desarrollo de modelos y prototipos editoriales', 'AV2004B', 5),
    ('Producción de narrativas convergentes multimodales', 'MI2008', 5),
    ('Fundamentos del periodismo hipermedia y transmedia', 'RI2004B', 5),
    ('Conflicto y negociación', 'RI2005B', 5),
    ('Cooperación y gobernanza global', 'RI2006B', 5),
    ('Gestión de bienes públicos globales en la sociedad de riesgo', 'RI2041', 5),
    ('Aspectos jurídicos de las relaciones internacionales', 'RI2042', 5),
    ('Organismos internacionales', 'RI2043', 5),
    ('Riesgos y amenazas en la agenda global contemporánea', 'TM2004', 5),
    ('Postproducción de audio para cine y video', 'TM2005B', 5),
    ('Diseño de aplicaciones interactivas de tecnología musical', 'TM2006B', 5),
    ('Musicalización de productos audiovisuales', 'TM2007B', 5),
    ('Producción y mercadotecnia audiovisual', 'EC2002B', 5),
    ('Economía conductual y neurociencia política', 'P2003B', 5),
    ('Políticas tecnológicas para el desarrollo', 'P2013', 5),
    ('Elección pública e instituciones políticas comparadas', 'TC2002B', 5),
    ('Ciencia de datos para la toma de decisiones II', 'AR3001B', 5),
    ('Metrópolis sostenible: Mitigación', 'AR3002B', 5),
    ('Metrópolis sostenible: Resiliencia', 'AR3004B', 5),
    ('Metrópolis sostenible: Adaptación', 'EC2033', 5),
    ('Economía urbana', 'Sexto Semestre', 5),
    ('VA3111', 'Tópicos I', 5),
    ('VA3112', 'Tópicos II', 5),
    ('VA3113', 'Tópicos III', 5),
    ('VA3114', 'Tópicos IV', 5),
    ('VA3115', 'Tópicos V', 5),
    ('VA3116', 'Tópicos VI', 5),
    ('OP3091', 'Optativa Profesional I', 5),
    ('OP3092', 'Optativa Profesional II', 5),
    ('OP3093', 'Optativa profesional III', 5),
    ('OP3094', 'Optativa profesional IV', 5),
    ('OP3095', 'Optativa profesional V', 5),
    ('OP3096', 'Optativa profesional VI', 5),
    ('IN2007B', 'Diseño disruptivo de procesos organizacionales', 5),
    ('IN2008B', 'Aseguramiento de la excelencia operacional', 5),
    ('IN2009B', 'Mejora de una cadena de valor adaptativa', 5),
    ('IN2042', 'Modelación de la cadena de valor', 5),
    ('IN2043', 'Simulación discreta, continua y por agentes', 5),
    ('IN2044', 'Diseño de un proceso de consultoría y gestión del cambio', 5),
    ('MR2007B', 'Automatización de sistemas de manufactura', 5),
    ('MR3001B', 'Diseño y desarrollo de robots', 5),
    ('AG3001B', 'Bioproducción en ambientes controlados', 5),
    ('TA3001B', 'Desarrollo sustentable de alimentos saludables y personalizados', 5),
    ('BT2006B', 'Diseño de biorreactores', 5),
    ('BT2007B', 'Diseño de estrategias de bioseparación', 5),
    ('BT2008B', 'Planeación de procesos biotecnológicos', 5),
    ('BT2024', 'Aplicación y análisis de las tecnologías ómicas', 5),
    ('BT2025', 'Prospección de bioprocesos', 5),
    ('CV2007B', 'Modelación de técnicas de saneamiento del agua', 5),
    ('CV2008B', 'Diseño de movilidad eficiente de personas y mercancías', 5),
    ('CV2009B', 'Diseño estructural con concreto reforzado y acero', 5),
    ('MA2006B', 'Uso de álgebras modernas para seguridad y criptografía', 5),
    ('MA2007B', 'Uso de geometría y topología para ciencia de datos', 5),
    ('MA2008B', 'Análisis numérico para la optimización no-lineal', 5),
    ('DS2002', 'Innovación de modelos de sustentabilidad corporativa', 5),
    ('IQ2005B', 'Dimensionamiento avanzado y monitoreo de procesos energéticos', 5),
    ('IQ2006B', 'Innovación de los procesos en su cadena de valor', 5),
    ('IQ2014', 'Mejora de procesos productivos aplicando principios de economía circular', 5),
    ('TE2010B', 'Desarrollo de sistemas de procesamiento digital de señales', 5),
    ('TE2011B', 'Diseño de sistemas de comunicaciones', 5),
    ('TE2012B', 'Análisis de sistemas energéticos', 5),
    ('F2008B', 'Caracterización experimental de sistemas ópticos', 5),
    ('F2009B', 'Caracterización experimental de materiales', 5),
    ('TE2001B', 'Caracterización experimental mediante instrumentación electrónica', 5),
    ('NN3001B', 'Gestión estratégica de la innovación tecnológica', 5),
    ('BI2007B', 'Análisis de sistemas de imagenología', 5),
    ('BI2008B', 'Aplicación de la Ingeniería tisular y bioimpresión', 5),
    ('BI2009B', 'Procesamiento de imágenes médicas para el diagnóstico', 5),
    ('BI2010B', 'Diseño y desarrollo en neuroingeniería', 5),
    ('BI2011B', 'Implementación de ingeniería clínica', 5),
    ('BI2012B', 'Análisis de la mecánica de biofluidos', 5),
    ('M2006B', 'Diseño de máquinas térmicas', 5),
    ('M2007B', 'Análisis y prevención de fallas', 5),
    ('M2008B', 'Diseño de elementos de máquinas', 5),
    ('NT2001', 'Diseño de dispositivos nanotecnológicos', 5),
    ('NT2002', 'Generación de prototipos y escalamiento de procesos', 5),
    ('NT2004B', 'Aplicación de nanodispositivos en soluciones integrales', 5),
    ('NT2005B', 'Aplicación de prototipado y escalamiento en soluciones integrales', 5),
    ('Q2003B', 'Aplicación de investigación en soluciones integrales', 5),
    ('Q2027', 'Investigación y diseño experimental', 5),
    ('IQ2013B', 'Diseño integral de procesos químicos', 5),
    ('IQ2017', 'Diseño de procesos químicos', 5),
    ('MR2021', 'Automatización y control de procesos químicos', 5),
    ('TE3001B', 'Fundamentación de robótica', 5),
    ('TE3002B', 'Implementación de robótica inteligente', 5),
    ('TC3001B', 'Desarrollo de software', 5),
    ('TI3001B', 'Administración estratégica y gobierno de tecnologías de información', 5),
    ('TI3002B', 'Innovación y diseño de iniciativas de transformación digital', 5),
    ('TI3003B', 'Aplicación de analítica y gobierno de datos', 5),
    ('AT3001B', 'Proyecto de arte digital', 5),
    ('DL3001B', 'Proyecto de diseño', 5),
    ('D3001B', 'Controles constitucionales I', 5),
    ('D3002B', 'Derecho administrativo II', 5),
    ('D3003B', 'Derecho procesal civil y mercantil', 5),
    ('D3039', 'Derecho fiscal', 5),
    ('D3040', 'Derecho procesal laboral', 5),
    ('D3041', 'Empresa y cumplimiento regulatorio', 5),
    ('D3042', 'Juicios orales', 5),
    ('D3043', 'Sistema penal acusatorio', 5),
    ('D3044', 'Sociedades mercantiles', 5),
    ('EC3001B', 'Análisis de decisiones bajo condiciones de incertidumbre', 5),
    ('P2020', 'Economía política del cambio tecnológico y el desarrollo', 5),
    ('P3001B', 'Gobierno, sector privado, tecnología y nuevos mercados', 5),
    ('TC3065', 'Experimentos e inferencia causal para política pública', 5),
    ('CF3001B', 'Formación de juicio crítico profesional', 7),
    ('CF3024', 'Aseguramiento e interés público', 7),
    ('CF3026', 'Ciclo tributario y empresas', 7),
    ('CF3027', 'Consolidación de información financiera', 7),
    ('D3004B', 'Controles constitucionales II', 7),
    ('D3005B', 'Derecho internacional privado y arbitraje comercial internacional', 7),
    ('D3006B', 'Derecho procesal fiscal y administrativo', 7),
    ('D3045', 'Derecho de la propiedad intelectual', 7),
    ('D3046', 'Derecho internacional público', 7),
    ('D3047', 'Ética para abogados', 7),
    ('D3048', 'Inglés legal', 7),
    ('D3049', 'Seminario de derecho internacional público', 7),
    ('D3050', 'Títulos y operaciones de crédito', 7),
    ('AR3003B', 'Gestión y administración de proyectos territoriales de inversión', 7),
    ('OP3001B', 'Optativa profesional multidisciplinaria', 8),
    ('AR3007B', 'Emprendimiento en el ámbito de la arquitectura', 8),
    ('AR3008B', 'Gestión arquitectónica', 8),
    ('NI3001B', 'Desarrollo de estrategias de internacionalización para el siglo XXI', 8),
    ('IN3001B', 'Diseño de un sistema organizacional inteligente', 8),
    ('MR3002B', 'Diseño e implementación de sistemas mecatrónicos', 8),
    ('AG3002B', 'Transformación digital de biosistemas productivos', 8),
    ('AG3003B', 'Gestión integral y ecoeficiente', 8),
    ('TA3002B', 'Administración de procesos de producción y distribución de alimentos', 8),
    ('BT3002B', 'Diseño de procesos biotecnológicos y de bioproductos', 8),
    ('CV3001B', 'Integración de proyectos de ingeniería civil', 8),
    ('MA3001B', 'Desarrollo de proyectos de ingeniería matemática', 8),
    ('DS3001B', 'Diseño de estrategias de sustentabilidad corporativa', 8),
    ('IQ3001B', 'Desarrollo de modelos de sustentabilidad energética', 8),
    ('TE3004B', 'Desarrollo de telecomunicaciones y sistemas energéticos', 8),
    ('F3001B', 'Integración de ingeniería física', 8),
    ('NN3002B', 'Desarrollo de proyecto integrador de innovación', 8),
    ('BI3001B', 'Desarrollo de dispositivos médicos', 8),
    ('M3001B', 'Diseño de máquinas', 8),
    ('Q3001B', 'Desarrollo de proyectos de nanotecnología', 8),
    ('IQ3002B', 'Aplicación de la ingeniería de procesos en proyectos industriales', 8),
    ('TE3003B', 'Integración de robótica y sistemas inteligentes', 8),
    ('TC3002B', 'Desarrollo de aplicaciones avanzadas de ciencias computacionales', 8),
    ('TC3003B', 'Implementación de redes de área amplia y servicios distribuidos', 8),
    ('TI3004B', 'Transformación digital de la organización', 8),
    ('AT3002B', 'Proyecto integral de arte digital', 8),
    ('AD3001B', 'Gestión estratégica de PYMES', 8),
    ('AD3002B', 'Institucionalización de la empresa familiar', 8),
    ('FZ3001B', 'Administración financiera internacional', 8),
    ('FZ3002B', 'Gestión de fondos de inversión', 8),
    ('CF3002B', 'Dirección financiera y contraloría estratégica', 8),
    ('CO3001B', 'Proyecto integrador de comunicación', 8),
    ('EM3001B', 'Escalabilidad', 8),
    ('EM3002B', 'Persuasión y ventas', 8),
    ('DL3002B', 'Proyecto integral de diseño', 8),
    ('RH3001B', 'Liderazgo estratégico del talento', 8),
    ('RH3002B', 'Potenciación de la cultura organizacional', 8),
    ('EC3002B', 'Solución y evaluación de problemas económicos', 8),
    ('ED3001B', 'Proyecto integrador de innovación educativa', 8),
    ('MT3001B', 'Liderazgo de mercadotecnia I', 8),
    ('MT3002B', 'Liderazgo de mercadotecnia II', 8),
    ('AD3003B', 'Planeación estratégica basada en analítica prescriptiva', 8),
    ('H3001B', 'Proyecto integrador de letras', 8),
    ('MI3001B', 'Proyecto integrador de periodismo', 8),
    ('RI3002B', 'Análisis y estrategias de política exterior', 8),
    ('TM3001B', 'Proyecto integrador de tecnología y producción musical', 8),
    ('P3002B', 'Diseño e implementación de innovaciones públicas', 8),
    ('AR3005B', 'Ciudades emergentes', 8),
    ('AR3006B', 'Complejidad y debate', 8),
    ('D3007B', 'Investigación jurídica aplicada', 9);
