INSERT INTO UnidadFormacion VALUES
    ('AC1001', 'Lógica computacional', 1),
    ('Lógica computacional', 'AC1001B', 1),
    ('AC1001B', 'Modelación de la física: Estática', 1),
    ('Modelación de la física: Estática', 'AC1002', 1),
    ('AC1002', 'Razonamiento matemático', 1),
    ('Razonamiento matemático', 'AC1002B', 1),
    ('AC1002B', 'Modelación de la física: Dinámica', 1),
    ('Modelación de la física: Dinámica', 'AR1002B', 1),
    ('AR1002B', 'Exploración en el hábitat: de la escala del elemento al territorio', 1),
    ('Exploración en el hábitat: de la escala del elemento al territorio', 'CV1009', 1),
    ('CV1009', 'Análisis químico del ambiente y de los materiales de construcción', 1),
    ('Análisis químico del ambiente y de los materiales de construcción', 'EG1001', 1),
    ('EG1001', 'Optativa de matemáticas y ciencias', 1),
    ('Optativa de matemáticas y ciencias', 'Segundo Semestre', 1),
    ('AC1003', 'Análisis con Probabilidad y Estadística', 2),
    ('Análisis con Probabilidad y Estadística', 'AC1003B', 2),
    ('AC1003B', 'Sistemas constructivos', 2),
    ('Sistemas constructivos', 'AC1004B', 2),
    ('AC1004B', 'Información espacial', 2),
    ('Información espacial', 'AC1005B', 2),
    ('AC1005B', 'Sistemas de información geográfica', 2),
    ('Sistemas de información geográfica', 'CV1010', 2),
    ('CV1010', 'Fundamentos de geología aplicada al ambiente construido', 2),
    ('Fundamentos de geología aplicada al ambiente construido', 'CV1011', 2),
    ('CV1011', 'Evaluación del impacto ambiental de proyectos territoriales', 2),
    ('Evaluación del impacto ambiental de proyectos territoriales', 'CV1012', 2),
    ('CV1012', 'Aplicación de métodos numéricos al ambiente construido', 2),
    ('Aplicación de métodos numéricos al ambiente construido', 'EG1002', 2),
    ('EG1002', 'Optativa de humanidades y bellas artes', 2),
    ('Optativa de humanidades y bellas artes', 'AR1025', 2),
    ('AR1025', 'Creatividad y diseño', 2),
    ('Creatividad y diseño', 'AR1026', 2),
    ('AR1026', 'Metodologías de investigación para proyectos de diseño', 2),
    ('Metodologías de investigación para proyectos de diseño', 'AR1027', 2),
    ('AR1027', 'Métodos de diseño', 2),
    ('Métodos de diseño', 'AR1028', 2),
    ('AR1028', 'Técnicas de representación espacial y de imagen', 2),
    ('Técnicas de representación espacial y de imagen', 'Tercer Semestre', 2),
    ('AR2002B', 'Diseño y construcción de un hábitat efímero', 3),
    ('Diseño y construcción de un hábitat efímero', 'AR2035', 3),
    ('AR2035', 'La conceptualización del espacio, su teoría y su historia', 3),
    ('La conceptualización del espacio, su teoría y su historia', 'AR2036', 3),
    ('AR2036', 'Representación de la arquitectura y su construcción', 3),
    ('Representación de la arquitectura y su construcción', 'EG1003', 3),
    ('EG1003', 'Optativa de ciencias sociales y del comportamiento', 3),
    ('Optativa de ciencias sociales y del comportamiento', 'VA1001B', 3),
    ('VA1001B', 'Tópico de exploración', 3),
    ('Tópico de exploración', 'Cuarto Semestre', 3),
    ('AR2004B', 'Arquitectura y contextos', 4),
    ('Arquitectura y contextos', 'AR2007B', 4),
    ('AR2007B', 'Equipamiento comunitario', 4),
    ('Equipamiento comunitario', 'AR2039', 4),
    ('AR2039', 'Investigación y proyecto arquitectónico', 4),
    ('Investigación y proyecto arquitectónico', 'EG1004', 4),
    ('EG1004', 'Optativa de liderazgo, emprendimiento e innovación', 4),
    ('Optativa de liderazgo, emprendimiento e innovación', 'Quinto Semestre', 4),
    ('AR2008B', 'Vivienda colectiva', 5),
    ('Vivienda colectiva', 'AR2009B', 5),
    ('AR2009B', 'Vivienda unifamiliar', 5),
    ('Vivienda unifamiliar', 'AR2040', 5),
    ('AR2040', 'Constructibilidad', 5),
    ('Constructibilidad', 'EG1005', 5),
    ('EG1005', 'Optativa de ética y ciudadanía', 5),
    ('Optativa de ética y ciudadanía', 'Sexto Semestre', 5),
    ('VA3111', 'Tópicos I', 6),
    ('Tópicos I', 'VA3112', 6),
    ('VA3112', 'Tópicos II', 6),
    ('Tópicos II', 'VA3113', 6),
    ('VA3113', 'Tópicos III', 6),
    ('Tópicos III', 'VA3114', 6),
    ('VA3114', 'Tópicos IV', 6),
    ('Tópicos IV', 'VA3115', 6),
    ('VA3115', 'Tópicos V', 6),
    ('Tópicos V', 'VA3116', 6),
    ('VA3116', 'Tópicos VI', 6),
    ('Tópicos VI', 'Séptimo Semestre', 6),
    ('OP3091', 'Optativa Profesional I', 7),
    ('Optativa Profesional I', 'OP3092', 7),
    ('OP3092', 'Optativa Profesional II', 7),
    ('Optativa Profesional II', 'OP3093', 7),
    ('OP3093', 'Optativa profesional III', 7),
    ('Optativa profesional III', 'OP3094', 7),
    ('OP3094', 'Optativa profesional IV', 7),
    ('Optativa profesional IV', 'OP3095', 7),
    ('OP3095', 'Optativa profesional V', 7),
    ('Optativa profesional V', 'OP3096', 7),
    ('OP3096', 'Optativa profesional VI', 7),
    ('Optativa profesional VI', 'Octavo Semestre', 7),
    ('OP3001B', 'Optativa profesional multidisciplinaria', 8),
    ('Optativa profesional multidisciplinaria', 'AR3007B', 8),
    ('AR3007B', 'Emprendimiento en el ámbito de la arquitectura', 8),
    ('Emprendimiento en el ámbito de la arquitectura', 'AR3008B', 8),
    ('AR3008B', 'Gestión arquitectónica', 8),
    ('Gestión arquitectónica', 'AD1000B', 8),
    ('AD1000B', 'El rol de los negocios en la sociedad', 8),
    ('El rol de los negocios en la sociedad', 'AD1014', 8),
    ('AD1014', 'Dirección de los negocios', 8),
    ('Dirección de los negocios', 'CF1015', 8),
    ('CF1015', 'Análisis financiero', 8),
    ('Análisis financiero', 'EC1017', 8),
    ('EC1017', 'Economía empresarial', 8),
    ('Economía empresarial', 'FZ1011', 8),
    ('FZ1011', 'Decisiones financieras', 8),
    ('Decisiones financieras', 'MA1027', 8),
    ('MA1027', 'NI1001B', 8),
    ('NI1001B', 'Globalización de los negocios', 8),
    ('Globalización de los negocios', 'RH1001B', 8),
    ('RH1001B', 'Estrategia y talento', 8),
    ('Estrategia y talento', 'TC1027', 8),
    ('TC1027', 'Programación para negocios', 8),
    ('Programación para negocios', 'AD1016', 8),
    ('AD1016', 'Comunicación que inspira', 8),
    ('Comunicación que inspira', 'CD1004', 8),
    ('CD1004', 'Análisis para la toma de decisiones', 8),
    ('Análisis para la toma de decisiones', 'CD1005', 8),
    ('CD1005', 'Pensamiento estadístico', 8),
    ('Pensamiento estadístico', 'CF1001B', 8),
    ('CF1001B', 'Dirección financiera', 8),
    ('Dirección financiera', 'D1029', 8),
    ('D1029', 'Legalidad y negocios responsables', 8),
    ('Legalidad y negocios responsables', 'EM1001B', 8),
    ('EM1001B', 'Ideación y prototipado', 8),
    ('Ideación y prototipado', 'EM1009', 8),
    ('EM1009', 'Innovación de modelos de negocios', 8),
    ('Innovación de modelos de negocios', 'MT1001B', 8),
    ('MT1001B', 'Descubrimientos del mercado para el desarrollo de estrategias', 8),
    ('Descubrimientos del mercado para el desarrollo de estrategias', 'RH1004', 8),
    ('RH1004', 'Procesos de gestión de talento', 8),
    ('Procesos de gestión de talento', 'AD1001B', 8),
    ('AD1001B', 'Creación de valor compartido', 8),
    ('Creación de valor compartido', 'CF1016', 8),
    ('CF1016', 'Estrategias de planeación financiera', 8),
    ('Estrategias de planeación financiera', 'EM1010', 8),
    ('EM1010', 'Proyecto de innovación empresarial', 8),
    ('Proyecto de innovación empresarial', 'FZ1012', 8),
    ('FZ1012', 'Evaluación de proyectos de inversión', 8),
    ('Evaluación de proyectos de inversión', 'MT1002B', 8),
    ('MT1002B', 'Construcción de soluciones para el mercado', 8),
    ('Construcción de soluciones para el mercado', 'MT1011', 8),
    ('MT1011', 'Estrategias de mercado y diferenciación', 8),
    ('Estrategias de mercado y diferenciación', 'NI1004', 8),
    ('NI1004', 'Competitividad internacional  y oportunidades de crecimiento', 8),
    ('Competitividad internacional  y oportunidades de crecimiento', 'RH1005', 8),
    ('RH1005', 'Dimensión estratégica del capital humano', 8),
    ('Dimensión estratégica del capital humano', 'NI2001B', 8),
    ('NI2001B', 'Panorama internacional de los negocios', 8),
    ('Panorama internacional de los negocios', 'NI2002B', 8),
    ('NI2002B', 'Plan de exportación', 8),
    ('Plan de exportación', 'NI2026', 8),
    ('NI2026', 'Negocios globales: tendencias y detección de riesgos', 8),
    ('Negocios globales: tendencias y detección de riesgos', 'NI2027', 8),
    ('NI2027', 'Operación logística internacional', 8),
    ('Operación logística internacional', 'NI2003B', 8),
    ('NI2003B', 'Administración de importaciones y sus regulaciones', 8),
    ('Administración de importaciones y sus regulaciones', 'NI2004B', 8),
    ('NI2004B', 'Desarrollo internacional de servicios', 8),
    ('Desarrollo internacional de servicios', 'NI2025', 8),
    ('NI2025', 'Negociación Intercultural', 8),
    ('Negociación Intercultural', 'NI2028', 8),
    ('NI2028', 'Ventas y contratos internacionales', 8),
    ('Ventas y contratos internacionales', 'NI3001B', 8),
    ('NI3001B', 'Desarrollo de estrategias de internacionalización para el siglo XXI', 8),
    ('Desarrollo de estrategias de internacionalización para el siglo XXI', 'F1001B', 8),
    ('F1001B', 'Modelación de la ingeniería y ciencias', 8),
    ('Modelación de la ingeniería y ciencias', 'F1006B', 8),
    ('F1006B', 'Modelación del movimiento en ingeniería', 8),
    ('Modelación del movimiento en ingeniería', 'F1007B', 8),
    ('F1007B', 'Aplicación de las leyes de conservación en sistemas ingenieriles', 8),
    ('Aplicación de las leyes de conservación en sistemas ingenieriles', 'MA1028', 8),
    ('MA1028', 'Modelación matemática fundamental', 8),
    ('Modelación matemática fundamental', 'Q1019', 8),
    ('Q1019', 'Análisis de la estructura, propiedades y transformación de la materia', 8),
    ('Análisis de la estructura, propiedades y transformación de la materia', 'TC1028', 8),
    ('TC1028', 'Pensamiento computacional para ingeniería', 8),
    ('Pensamiento computacional para ingeniería', 'F1008', 8),
    ('F1008', 'Experimentación física y pensamiento estadístico', 8),
    ('Experimentación física y pensamiento estadístico', 'F1015B', 8),
    ('F1015B', 'Aplicación de la termodinámica en sistemas ingenieriles', 8),
    ('Aplicación de la termodinámica en sistemas ingenieriles', 'F1016B', 8),
    ('F1016B', 'Análisis de sistemas eléctricos en sistemas ingenieriles', 8),
    ('Análisis de sistemas eléctricos en sistemas ingenieriles', 'F1017B', 8),
    ('F1017B', 'Análisis de sistemas electromagnéticos en sistemas ingenieriles', 8),
    ('Análisis de sistemas electromagnéticos en sistemas ingenieriles', 'MA1029', 8),
    ('MA1029', 'Modelación matemática intermedia', 8),
    ('Modelación matemática intermedia', 'MA1030', 8),
    ('MA1030', 'Modelación matricial', 8),
    ('Modelación matricial', 'MA1031', 8),
    ('MA1031', 'Análisis estadístico', 8),
    ('Análisis estadístico', 'Q1021', 8),
    ('Q1021', 'Experimentación química y pensamiento estadístico fundamental', 8),
    ('Experimentación química y pensamiento estadístico fundamental', 'IN1001B', 8),
    ('IN1001B', 'Diseño y análisis de experimentos para la innovación ingenieril', 8),
    ('Diseño y análisis de experimentos para la innovación ingenieril', 'IN1002B', 8),
    ('IN1002B', 'Desarrollo de proyectos de análisis de datos', 8),
    ('Desarrollo de proyectos de análisis de datos', 'M1011', 8),
    ('M1011', 'Análisis de equilibrio estático', 8),
    ('Análisis de equilibrio estático', 'MA1034', 8),
    ('MA1034', 'Modelación de procesos mediante algebra lineal', 8),
    ('Modelación de procesos mediante algebra lineal', 'MA1035', 8),
    ('MA1035', 'Modelación en ingeniería mediante sistemas dinámicos', 8),
    ('Modelación en ingeniería mediante sistemas dinámicos', 'TE1020', 8),
    ('TE1020', 'Análisis de circuitos eléctricos', 8),
    ('Análisis de circuitos eléctricos', 'IN2001B', 8),
    ('IN2001B', 'Desarrollo de proyectos con visión sistémica', 8),
    ('Desarrollo de proyectos con visión sistémica', 'IN2002B', 8),
    ('IN2002B', 'Mejora de un proceso organizacional con métodos estadísticos', 8),
    ('Mejora de un proceso organizacional con métodos estadísticos', 'IN2003B', 8),
    ('IN2003B', 'Conceptualización de procesos con enfoque innovador', 8),
    ('Conceptualización de procesos con enfoque innovador', 'IN2032', 8),
    ('IN2032', 'Análisis estadístico de datos', 8),
    ('Análisis estadístico de datos', 'IN2037', 8),
    ('IN2037', 'Diseño de sistemas ciberfísicos', 8),
    ('Diseño de sistemas ciberfísicos', 'IN2038', 8),
    ('IN2038', 'Evaluación económica de proyectos', 8),
    ('Evaluación económica de proyectos', 'IN2004B', 8),
    ('IN2004B', 'Generación de valor con analítica de datos', 8),
    ('Generación de valor con analítica de datos', 'IN2005B', 8),
    ('IN2005B', 'Evaluación de la competitividad organizacional', 8),
    ('Evaluación de la competitividad organizacional', 'IN2006B', 8),
    ('IN2006B', 'Análisis de la viabilidad de proyectos con perspectiva sistémica', 8),
    ('Análisis de la viabilidad de proyectos con perspectiva sistémica', 'IN2039', 8),
    ('IN2039', 'Visualización de datos para la toma de decisiones', 8),
    ('Visualización de datos para la toma de decisiones', 'IN2040', 8),
    ('IN2040', 'Optimización de procesos organizacionales', 8),
    ('Optimización de procesos organizacionales', 'IN2041', 8),
    ('IN2041', 'Mejora de procesos con métodos heurísticos y metaheurísticos', 8),
    ('Mejora de procesos con métodos heurísticos y metaheurísticos', 'Sexto Semestre', 8),
    ('IN2007B', 'Diseño disruptivo de procesos organizacionales', 6),
    ('Diseño disruptivo de procesos organizacionales', 'IN2008B', 6),
    ('IN2008B', 'Aseguramiento de la excelencia operacional', 6),
    ('Aseguramiento de la excelencia operacional', 'IN2009B', 6),
    ('IN2009B', 'Mejora de una cadena de valor adaptativa', 6),
    ('Mejora de una cadena de valor adaptativa', 'IN2042', 6),
    ('IN2042', 'Modelación de la cadena de valor', 6),
    ('Modelación de la cadena de valor', 'IN2043', 6),
    ('IN2043', 'Simulación discreta, continua y por agentes', 6),
    ('Simulación discreta, continua y por agentes', 'IN2044', 6),
    ('IN2044', 'Diseño de un proceso de consultoría y gestión del cambio', 6),
    ('Diseño de un proceso de consultoría y gestión del cambio', 'IN3001B', 6),
    ('IN3001B', 'Diseño de un sistema organizacional inteligente', 6),
    ('Diseño de un sistema organizacional inteligente', 'M2001B', 6),
    ('M2001B', 'Análisis de materiales y manufactura', 6),
    ('Análisis de materiales y manufactura', 'M2005', 6),
    ('M2005', 'Análisis  de mecanismos', 6),
    ('Análisis  de mecanismos', 'MR2003B', 6),
    ('MR2003B', 'Integración mecatrónica', 6),
    ('Integración mecatrónica', 'MR2004B', 6),
    ('MR2004B', 'Implementación de sistemas mecatrónicos', 6),
    ('Implementación de sistemas mecatrónicos', 'MR2022', 6),
    ('MR2022', 'Análisis de elementos de la mecatrónica', 6),
    ('Análisis de elementos de la mecatrónica', 'MR2023', 6),
    ('MR2023', 'Modelación y automatización', 6),
    ('Modelación y automatización', 'MR2005B', 6),
    ('MR2005B', 'Solución de problemas de procesos', 6),
    ('Solución de problemas de procesos', 'MR2006B', 6),
    ('MR2006B', 'Automatización industrial', 6),
    ('Automatización industrial', 'MR2024', 6),
    ('MR2024', 'Diseño mecatrónico', 6),
    ('Diseño mecatrónico', 'MR2025', 6),
    ('MR2025', 'Diseño de sistemas de control', 6),
    ('Diseño de sistemas de control', 'MR2007B', 6),
    ('MR2007B', 'Automatización de sistemas de manufactura', 6),
    ('Automatización de sistemas de manufactura', 'MR3001B', 6),
    ('MR3001B', 'Diseño y desarrollo de robots', 6),
    ('Diseño y desarrollo de robots', 'MR3002B', 6),
    ('MR3002B', 'Diseño e implementación de sistemas mecatrónicos', 6),
    ('Diseño e implementación de sistemas mecatrónicos', 'EC1001B', 6),
    ('EC1001B', 'Transformación del México contemporáneo', 6),
    ('Transformación del México contemporáneo', 'MA1022', 6),
    ('MA1022', 'Pensamiento matemático I', 6),
    ('Pensamiento matemático I', 'P1010', 6),
    ('P1010', 'Filosofía política para los dilemas contemporáneos', 6),
    ('Filosofía política para los dilemas contemporáneos', 'P1011', 6),
    ('P1011', 'Introducción a las ciencias sociales', 6),
    ('Introducción a las ciencias sociales', 'RI1001B', 6),
    ('RI1001B', 'Desafíos globales', 6),
    ('Desafíos globales', 'TC1001B', 6),
    ('TC1001B', 'Principios de programación para las ciencias sociales', 6),
    ('Principios de programación para las ciencias sociales', 'D1001B', 6),
    ('D1001B', 'Introducción al derecho', 6),
    ('Introducción al derecho', 'EC1002B', 6),
    ('EC1002B', 'Emprendimiento y tecnología para la transformación de México', 6),
    ('Emprendimiento y tecnología para la transformación de México', 'EC1013', 6),
    ('EC1013', 'Macroeconomía', 6),
    ('Macroeconomía', 'EC1014', 6),
    ('EC1014', 'Microeconomía', 6),
    ('Microeconomía', 'MA1023', 6),
    ('MA1023', 'Métodos cuantitativos I', 6),
    ('Métodos cuantitativos I', 'MA1024', 6),
    ('MA1024', 'Pensamiento matemático II', 6),
    ('Pensamiento matemático II', 'TC1002B', 6),
    ('TC1002B', 'Herramientas tecnológicas para las ciencias sociales', 6),
    ('Herramientas tecnológicas para las ciencias sociales', 'EC1003B', 6),
    ('EC1003B', 'Macroeconomía y desarrollo económico', 6),
    ('Macroeconomía y desarrollo económico', 'EC1015', 6),
    ('EC1015', 'Economía conductual', 6),
    ('Economía conductual', 'EC1016', 6),
    ('EC1016', 'Economía para la toma de decisiones', 6),
    ('Economía para la toma de decisiones', 'MA1025', 6),
    ('MA1025', 'Métodos cuantitativos II', 6),
    ('Métodos cuantitativos II', 'MA1026', 6),
    ('MA1026', 'Pensamiento matemático III', 6),
    ('Pensamiento matemático III', 'P1001B', 6),
    ('P1001B', 'Participación política y sociología de la identidad', 6),
    ('Participación política y sociología de la identidad', 'A1004', 6),
    ('A1004', 'Cultura visual y sonora', 6),
    ('Cultura visual y sonora', 'AV1002B', 6),
    ('AV1002B', 'Técnicas y discursos fotográficos', 6),
    ('Técnicas y discursos fotográficos', 'CO1001B', 6),
    ('CO1001B', 'Metodologías de investigación de factores humanos', 6),
    ('Metodologías de investigación de factores humanos', 'DL1022', 6),
    ('DL1022', 'Metodologías del pensamiento creativo', 6),
    ('Metodologías del pensamiento creativo', 'EH1001B', 6),
    ('EH1001B', 'Inmersión y experimentación creativa', 6),
    ('Inmersión y experimentación creativa', 'AR1001B', 6),
    ('AR1001B', 'Representación formal del espacio', 6),
    ('Representación formal del espacio', 'AV1001B', 6),
    ('AV1001B', 'Narrativa audiovisual', 6),
    ('Narrativa audiovisual', 'EH1008', 6),
    ('EH1008', 'Imaginarios culturales de México', 6),
    ('Imaginarios culturales de México', 'EH1009', 6),
    ('EH1009', 'Semiótica y narratologías contemporáneas', 6),
    ('Semiótica y narratologías contemporáneas', 'H1001B', 6),
    ('H1001B', 'Estructuras simbólicas en la imagen, la literatura y la música', 6),
    ('Estructuras simbólicas en la imagen, la literatura y la música', 'F1002B', 6),
    ('F1002B', 'Modelación del movimiento en bioingeniería y procesos químicos', 6),
    ('Modelación del movimiento en bioingeniería y procesos químicos', 'F1003B', 6),
    ('F1003B', 'Aplicación de las leyes de conservación en ingeniería de procesos', 6),
    ('Aplicación de las leyes de conservación en ingeniería de procesos', 'F1010B', 6),
    ('F1010B', 'Aplicación de la termodinámica en ingeniería de procesos', 6),
    ('Aplicación de la termodinámica en ingeniería de procesos', 'F1011B', 6),
    ('F1011B', 'Análisis de sistemas eléctricos en ingeniería de procesos', 6),
    ('Análisis de sistemas eléctricos en ingeniería de procesos', 'F1012B', 6),
    ('F1012B', 'Análisis de sistemas electromagnéticos en ingeniería de procesos', 6),
    ('Análisis de sistemas electromagnéticos en ingeniería de procesos', 'Q1022', 6),
    ('Q1022', 'Análisis de la transformación de la materia en procesos químicos', 6),
    ('Análisis de la transformación de la materia en procesos químicos', 'Q1023', 6),
    ('Q1023', 'Experimentación química y pensamiento estadístico intermedio', 6),
    ('Experimentación química y pensamiento estadístico intermedio', 'BT1014', 6),
    ('BT1014', 'Fundamentación de la biología molecular', 6),
    ('Fundamentación de la biología molecular', 'IQ1001B', 6),
    ('IQ1001B', 'Aplicación de la conservación de la materia en ingeniería de procesos', 6),
    ('Aplicación de la conservación de la materia en ingeniería de procesos', 'IQ1002B', 6),
    ('IQ1002B', 'Aplicación de la conservación de la energía en ingeniería de procesos', 6),
    ('Aplicación de la conservación de la energía en ingeniería de procesos', 'Q1024', 6),
    ('Q1024', 'Aplicación del análisis químico', 6),
    ('Aplicación del análisis químico', 'Q1025', 6),
    ('Q1025', 'Experimentación en química analítica', 6),
    ('Experimentación en química analítica', 'Q1026', 6),
    ('Q1026', 'Análisis estructural de moléculas orgánicas y sus propiedades', 6),
    ('Análisis estructural de moléculas orgánicas y sus propiedades', 'Q1027', 6),
    ('Q1027', 'Fundamentación de la estructura y propiedades de biomoléculas', 6),
    ('Fundamentación de la estructura y propiedades de biomoléculas', 'AG2001B', 6),
    ('AG2001B', 'Análisis de biosistemas productivos', 6),
    ('Análisis de biosistemas productivos', 'AG2002B', 6),
    ('AG2002B', 'Evaluación de nutrición y sanidad en los biosistemas', 6),
    ('Evaluación de nutrición y sanidad en los biosistemas', 'AG2029', 6),
    ('AG2029', 'Fundamentación de biosistemas productivos', 6),
    ('Fundamentación de biosistemas productivos', 'AG2030', 6),
    ('AG2030', 'Integración de procesos bioproductivos', 6),
    ('Integración de procesos bioproductivos', 'DS2001B', 6),
    ('DS2001B', 'Conservación de recursos naturales en biosistemas', 6),
    ('Conservación de recursos naturales en biosistemas', 'IN2033', 6),
    ('IN2033', 'Gestión de biosistemas productivos', 6),
    ('Gestión de biosistemas productivos', 'AG2003B', 6),
    ('AG2003B', 'Integración de tecnologías sustentables en biosistemas', 6),
    ('Integración de tecnologías sustentables en biosistemas', 'BT2001B', 6),
    ('BT2001B', 'Mejora de biosistemas con genética y biotecnología', 6),
    ('Mejora de biosistemas con genética y biotecnología', 'IN2034', 6),
    ('IN2034', 'Evaluación de la productividad', 6),
    ('Evaluación de la productividad', 'IN2035', 6),
    ('IN2035', 'Gestión avanzada de la producción', 6),
    ('Gestión avanzada de la producción', 'IN2036', 6),
    ('IN2036', 'Aplicación de metrología en biosistemas productivos', 6),
    ('Aplicación de metrología en biosistemas productivos', 'MR2001B', 6),
    ('MR2001B', 'Aplicación de automatización y control en biosistemas', 6),
    ('Aplicación de automatización y control en biosistemas', 'AG3001B', 6),
    ('AG3001B', 'Bioproducción en ambientes controlados', 6),
    ('Bioproducción en ambientes controlados', 'AG3002B', 6),
    ('AG3002B', 'Transformación digital de biosistemas productivos', 6),
    ('Transformación digital de biosistemas productivos', 'AG3003B', 6),
    ('AG3003B', 'Gestión integral y ecoeficiente', 6),
    ('Gestión integral y ecoeficiente', 'TA2001B', 6),
    ('TA2001B', 'Diseño de alimentos saludables', 6),
    ('Diseño de alimentos saludables', 'TA2002B', 6),
    ('TA2002B', 'Planeación de sistemas de distribución de alimentos', 6),
    ('Planeación de sistemas de distribución de alimentos', 'TA2003B', 6),
    ('TA2003B', 'Evaluación de factibilidad de nuevos productos', 6),
    ('Evaluación de factibilidad de nuevos productos', 'TA2017', 6),
    ('TA2017', 'Diseño sustentable en procesamiento de alimentos', 6),
    ('Diseño sustentable en procesamiento de alimentos', 'TA2018', 6),
    ('TA2018', 'Optimización de procesos y sistemas de inocuidad', 6),
    ('Optimización de procesos y sistemas de inocuidad', 'TA2019', 6),
    ('TA2019', 'Análisis fisicoquímico en el diseño de alimentos', 6),
    ('Análisis fisicoquímico en el diseño de alimentos', 'TA2004B', 6),
    ('TA2004B', 'Diseño de procesos sustentables', 6),
    ('Diseño de procesos sustentables', 'TA2005B', 6),
    ('TA2005B', 'Análisis del consumidor y mercado de alimentos', 6),
    ('Análisis del consumidor y mercado de alimentos', 'TA2006B', 6),
    ('TA2006B', 'Diseño de sistemas de administración de procesos e inocuidad', 6),
    ('Diseño de sistemas de administración de procesos e inocuidad', 'TA2020', 6),
    ('TA2020', 'Administración de procesos y sistemas de inocuidad', 6),
    ('Administración de procesos y sistemas de inocuidad', 'TA2021', 6),
    ('TA2021', 'Aplicación del análisis sensorial en alimentos', 6),
    ('Aplicación del análisis sensorial en alimentos', 'TA2022', 6),
    ('TA2022', 'Simulación de procesos de transformación de alimentos', 6),
    ('Simulación de procesos de transformación de alimentos', 'TA3001B', 6),
    ('TA3001B', 'Desarrollo sustentable de alimentos saludables y personalizados', 6),
    ('Desarrollo sustentable de alimentos saludables y personalizados', 'TA3002B', 6),
    ('TA3002B', 'Administración de procesos de producción y distribución de alimentos', 6),
    ('Administración de procesos de producción y distribución de alimentos', 'Q1028', 6),
    ('Q1028', 'Fundamentación de la estructura y transformación de la materia', 6),
    ('Fundamentación de la estructura y transformación de la materia', 'Q1029', 6),
    ('Q1029', 'Análisis de la estructura y transformación de la materia', 6),
    ('Análisis de la estructura y transformación de la materia', 'BT2002B', 6),
    ('BT2002B', 'Elaboración de productos biotecnológicos', 6),
    ('Elaboración de productos biotecnológicos', 'BT2003B', 6),
    ('BT2003B', 'Síntesis de biofábricas', 6),
    ('Síntesis de biofábricas', 'BT2019', 6),
    ('BT2019', 'Análisis y estudio de biosistemas', 6),
    ('Análisis y estudio de biosistemas', 'BT2020', 6),
    ('BT2020', 'Aplicación de bases moleculares', 6),
    ('Aplicación de bases moleculares', 'BT2004B', 6),
    ('BT2004B', 'Experimentación in vitro', 6),
    ('Experimentación in vitro', 'BT2005B', 6),
    ('BT2005B', 'Integración de operaciones de transferencia', 6),
    ('Integración de operaciones de transferencia', 'BT2026', 6),
    ('BT2026', 'Análisis de fenómenos de transporte', 6),
    ('Análisis de fenómenos de transporte', 'BT2006B', 6),
    ('BT2006B', 'Diseño de biorreactores', 6),
    ('Diseño de biorreactores', 'BT2007B', 6),
    ('BT2007B', 'Diseño de estrategias de bioseparación', 6),
    ('Diseño de estrategias de bioseparación', 'BT2008B', 6),
    ('BT2008B', 'Planeación de procesos biotecnológicos', 6),
    ('Planeación de procesos biotecnológicos', 'BT2024', 6),
    ('BT2024', 'Aplicación y análisis de las tecnologías ómicas', 6),
    ('Aplicación y análisis de las tecnologías ómicas', 'BT2025', 6),
    ('BT2025', 'Prospección de bioprocesos', 6),
    ('Prospección de bioprocesos', 'BT3002B', 6),
    ('BT3002B', 'Diseño de procesos biotecnológicos y de bioproductos', 6),
    ('Diseño de procesos biotecnológicos y de bioproductos', 'F1008B', 6),
    ('F1008B', 'Modelación del movimiento en ciencias', 6),
    ('Modelación del movimiento en ciencias', 'F1009B', 6),
    ('F1009B', 'Aplicación de las leyes de conservación en ciencias', 6),
    ('Aplicación de las leyes de conservación en ciencias', 'F1018B', 6),
    ('F1018B', 'Aplicación de la termodinámica en ciencias', 6),
    ('Aplicación de la termodinámica en ciencias', 'F1019B', 6),
    ('F1019B', 'Análisis de sistemas eléctricos en ciencias', 6),
    ('Análisis de sistemas eléctricos en ciencias', 'F1020B', 6),
    ('F1020B', 'Análisis de sistemas electromagnéticos en ciencias', 6),
    ('Análisis de sistemas electromagnéticos en ciencias', 'F1009', 6),
    ('F1009', 'Análisis de métodos matemáticos para la física', 6),
    ('Análisis de métodos matemáticos para la física', 'F1010', 6),
    ('F1010', 'Modelación con ecuaciones diferenciales', 6),
    ('Modelación con ecuaciones diferenciales', 'MA1001B', 6),
    ('MA1001B', 'Modelación estadística para la toma de decisiones', 6),
    ('Modelación estadística para la toma de decisiones', 'MA1002B', 6),
    ('MA1002B', 'Modelación de sistemas con ecuaciones diferenciales', 6),
    ('Modelación de sistemas con ecuaciones diferenciales', 'MA1036', 6),
    ('MA1036', 'Fundamentación del álgebra lineal', 6),
    ('Fundamentación del álgebra lineal', 'F1004B', 6),
    ('F1004B', 'Modelación computacional del movimiento', 6),
    ('Modelación computacional del movimiento', 'F1005B', 6),
    ('F1005B', 'Modelación computacional aplicando leyes de conservación', 6),
    ('Modelación computacional aplicando leyes de conservación', 'TC1033', 6),
    ('TC1033', 'Pensamiento computacional orientado a objetos', 6),
    ('Pensamiento computacional orientado a objetos', 'BT1013', 6),
    ('BT1013', 'Análisis de biología computacional', 6),
    ('Análisis de biología computacional', 'F1013B', 6),
    ('F1013B', 'Modelación computacional de sistemas eléctricos', 6),
    ('Modelación computacional de sistemas eléctricos', 'F1014B', 6),
    ('F1014B', 'Modelación computacional de sistemas electromagnéticos', 6),
    ('Modelación computacional de sistemas electromagnéticos', 'TC1003B', 6),
    ('TC1003B', 'Modelación de la ingeniería con matemática computacional', 6),
    ('Modelación de la ingeniería con matemática computacional', 'TC1030', 6),
    ('TC1030', 'Programación orientada a objetos', 6),
    ('Programación orientada a objetos', 'MA1033', 6),
    ('MA1033', 'Análisis de ecuaciones diferenciales', 6),
    ('Análisis de ecuaciones diferenciales', 'TC1004B', 6),
    ('TC1004B', 'Implementación de internet de las cosas', 6),
    ('Implementación de internet de las cosas', 'TC1031', 6),
    ('TC1031', 'Programación de estructuras de datos y algoritmos fundamentales', 6),
    ('Programación de estructuras de datos y algoritmos fundamentales', 'TC1032', 6),
    ('TC1032', 'Modelación de sistemas mínimos y arquitecturas computacionales', 6),
    ('Modelación de sistemas mínimos y arquitecturas computacionales', 'TI1015', 6),
    ('TI1015', 'Análisis de requerimientos de software', 6),
    ('Análisis de requerimientos de software', 'CV2001B', 6),
    ('CV2001B', 'Análisis de la interacción del ambiente construido y el entorno', 6),
    ('Análisis de la interacción del ambiente construido y el entorno', 'CV2002B', 6),
    ('CV2002B', 'Evaluación del comportamiento de materiales en estructuras', 6),
    ('Evaluación del comportamiento de materiales en estructuras', 'CV2003B', 6),
    ('CV2003B', 'Análisis del comportamiento de sistemas hidráulicos', 6),
    ('Análisis del comportamiento de sistemas hidráulicos', 'CV2035', 6),
    ('CV2035', 'Modelación de la información en la construcción', 6),
    ('Modelación de la información en la construcción', 'CV2036', 6),
    ('CV2036', 'Gestión de costos', 6),
    ('Gestión de costos', 'CV2037', 6),
    ('CV2037', 'Planeación y control de obra', 6),
    ('Planeación y control de obra', 'CV2004B', 6),
    ('CV2004B', 'Evaluación del comportamiento de sistemas estructurales', 6),
    ('Evaluación del comportamiento de sistemas estructurales', 'CV2005B', 6),
    ('CV2005B', 'Diseño de sistemas hidráulicos para el uso sustentable del agua', 6),
    ('Diseño de sistemas hidráulicos para el uso sustentable del agua', 'CV2006B', 6),
    ('CV2006B', 'Diseño de vialidades para el desarrollo', 6),
    ('Diseño de vialidades para el desarrollo', 'CV2038', 6),
    ('CV2038', 'Gestión de proyectos', 6),
    ('Gestión de proyectos', 'CV2039', 6),
    ('CV2039', 'Gestión de operaciones de construcción', 6),
    ('Gestión de operaciones de construcción', 'CV2040', 6),
    ('CV2040', 'Gestión empresarial en la industria de la construcción', 6),
    ('Gestión empresarial en la industria de la construcción', 'CV2007B', 6),
    ('CV2007B', 'Modelación de técnicas de saneamiento del agua', 6),
    ('Modelación de técnicas de saneamiento del agua', 'CV2008B', 6),
    ('CV2008B', 'Diseño de movilidad eficiente de personas y mercancías', 6),
    ('Diseño de movilidad eficiente de personas y mercancías', 'CV2009B', 6),
    ('CV2009B', 'Diseño estructural con concreto reforzado y acero', 6),
    ('Diseño estructural con concreto reforzado y acero', 'CV3001B', 6),
    ('CV3001B', 'Integración de proyectos de ingeniería civil', 6),
    ('Integración de proyectos de ingeniería civil', 'Q1020', 6),
    ('Q1020', 'Análisis de la estructura y propiedades de la materia', 6),
    ('Análisis de la estructura y propiedades de la materia', 'TC1029', 6),
    ('TC1029', 'Pensamiento computacional y programación', 6),
    ('Pensamiento computacional y programación', 'MA2001B', 6),
    ('MA2001B', 'Optimización determinista', 6),
    ('Optimización determinista', 'MA2002B', 6),
    ('MA2002B', 'Análisis de criptografía y seguridad', 6),
    ('Análisis de criptografía y seguridad', 'TC2004B', 6),
    ('TC2004B', 'Análisis de ciencia de datos', 6),
    ('Análisis de ciencia de datos', 'TC2032', 6),
    ('TC2032', 'Diseño de agentes inteligentes', 6),
    ('Diseño de agentes inteligentes', 'TC2033', 6),
    ('TC2033', 'Análisis de sistemas basados en conocimiento', 6),
    ('Análisis de sistemas basados en conocimiento', 'TC2034', 6),
    ('TC2034', 'Modelación del aprendizaje con inteligencia artificial', 6),
    ('Modelación del aprendizaje con inteligencia artificial', 'MA2003B', 6),
    ('MA2003B', 'Aplicación de métodos multivariados en ciencia de datos', 6),
    ('Aplicación de métodos multivariados en ciencia de datos', 'MA2004B', 6),
    ('MA2004B', 'Optimización estocástica', 6),
    ('Optimización estocástica', 'MA2005B', 6),
    ('MA2005B', 'Aplicación de criptografía y seguridad', 6),
    ('Aplicación de criptografía y seguridad', 'MA2014', 6),
    ('MA2014', 'Análisis de métodos de razonamiento e incertidumbre', 6),
    ('Análisis de métodos de razonamiento e incertidumbre', 'MA2015', 6),
    ('MA2015', 'Diseño de algoritmos matemáticos bioinspirados', 6),
    ('Diseño de algoritmos matemáticos bioinspirados', 'TC2035', 6),
    ('TC2035', 'Diseño de redes neuronales y aprendizaje profundo', 6),
    ('Diseño de redes neuronales y aprendizaje profundo', 'MA2006B', 6),
    ('MA2006B', 'Uso de álgebras modernas para seguridad y criptografía', 6),
    ('Uso de álgebras modernas para seguridad y criptografía', 'MA2007B', 6),
    ('MA2007B', 'Uso de geometría y topología para ciencia de datos', 6),
    ('Uso de geometría y topología para ciencia de datos', 'MA2008B', 6),
    ('MA2008B', 'Análisis numérico para la optimización no-lineal', 6),
    ('Análisis numérico para la optimización no-lineal', 'MA3001B', 6),
    ('MA3001B', 'Desarrollo de proyectos de ingeniería matemática', 6),
    ('Desarrollo de proyectos de ingeniería matemática', 'DS1008', 6),
    ('DS1008', 'Evaluación del capital natural y principios de sustentabilidad', 6),
    ('Evaluación del capital natural y principios de sustentabilidad', 'DS2002B', 6),
    ('DS2002B', 'Implementación de programas de manejo de recursos', 6),
    ('Implementación de programas de manejo de recursos', 'IQ2001B', 6),
    ('IQ2001B', 'Integración de procesos energéticos', 6),
    ('Integración de procesos energéticos', 'IQ2002B', 6),
    ('IQ2002B', 'Dimensionamiento de procesos energéticos', 6),
    ('Dimensionamiento de procesos energéticos', 'IQ2009', 6),
    ('IQ2009', 'Análisis termodinámico de procesos energéticos', 6),
    ('Análisis termodinámico de procesos energéticos', 'IQ2010', 6),
    ('IQ2010', 'Diseño de procesos para el transporte de fluidos', 6),
    ('Diseño de procesos para el transporte de fluidos', 'IQ2011', 6),
    ('IQ2011', 'Diseño de procesos de transferencia de calor', 6),
    ('Diseño de procesos de transferencia de calor', 'IQ2003B', 6),
    ('IQ2003B', 'Evaluación de procesos energéticos', 6),
    ('Evaluación de procesos energéticos', 'IQ2004B', 6),
    ('IQ2004B', 'Evaluación del desempeño energético de procesos industriales', 6),
    ('Evaluación del desempeño energético de procesos industriales', 'IQ2012', 6),
    ('IQ2012', 'Aplicación de los principios de eficiencia energética', 6),
    ('Aplicación de los principios de eficiencia energética', 'IQ2013', 6),
    ('IQ2013', 'Análisis de procesos y economía circular', 6),
    ('Análisis de procesos y economía circular', 'DS2002', 6),
    ('DS2002', 'Innovación de modelos de sustentabilidad corporativa', 6),
    ('Innovación de modelos de sustentabilidad corporativa', 'IQ2005B', 6),
    ('IQ2005B', 'Dimensionamiento avanzado y monitoreo de procesos energéticos', 6),
    ('Dimensionamiento avanzado y monitoreo de procesos energéticos', 'IQ2006B', 6),
    ('IQ2006B', 'Innovación de los procesos en su cadena de valor', 6),
    ('Innovación de los procesos en su cadena de valor', 'IQ2014', 6),
    ('IQ2014', 'Mejora de procesos productivos aplicando principios de economía circular', 6),
    ('Mejora de procesos productivos aplicando principios de economía circular', 'DS3001B', 6),
    ('DS3001B', 'Diseño de estrategias de sustentabilidad corporativa', 6),
    ('Diseño de estrategias de sustentabilidad corporativa', 'IQ3001B', 6),
    ('IQ3001B', 'Desarrollo de modelos de sustentabilidad energética', 6),
    ('Desarrollo de modelos de sustentabilidad energética', 'TE2005B', 6),
    ('TE2005B', 'Aplicación de la teoría electromagnética', 6),
    ('Aplicación de la teoría electromagnética', 'TE2006B', 6),
    ('TE2006B', 'Evaluación de circuitos eléctricos', 6),
    ('Evaluación de circuitos eléctricos', 'TE2007B', 6),
    ('TE2007B', 'Aplicación de dispositivos electrónicos', 6),
    ('Aplicación de dispositivos electrónicos', 'TE2047', 6),
    ('TE2047', 'Análisis de circuitos eléctricos de corriente alterna', 6),
    ('Análisis de circuitos eléctricos de corriente alterna', 'TE2048', 6),
    ('TE2048', 'Análisis de sistemas lógicos y circuitos digitales', 6),
    ('Análisis de sistemas lógicos y circuitos digitales', 'TE2049', 6),
    ('TE2049', 'Fundamentación de la física de estado sólido y optoelectrónica', 6),
    ('Fundamentación de la física de estado sólido y optoelectrónica', 'TC2009B', 6),
    ('TC2009B', 'Diseño usando microcontroladores y arquitectura computacional', 6),
    ('Diseño usando microcontroladores y arquitectura computacional', 'TC2039', 6),
    ('TC2039', 'Desarrollo de sistemas digitales', 6),
    ('Desarrollo de sistemas digitales', 'TE2008B', 6),
    ('TE2008B', 'Evaluación de Dispositivos Electrónicos', 6),
    ('Evaluación de Dispositivos Electrónicos', 'TE2009B', 6),
    ('TE2009B', 'Análisis de sistemas y dispositivos electrónicos de control', 6),
    ('Análisis de sistemas y dispositivos electrónicos de control', 'TE2046', 6),
    ('TE2046', 'Análisis de señales y sistemas', 6),
    ('Análisis de señales y sistemas', 'TE2050', 6),
    ('TE2050', 'Diseño de circuitos electrónicos', 6),
    ('Diseño de circuitos electrónicos', 'TE2010B', 6),
    ('TE2010B', 'Desarrollo de sistemas de procesamiento digital de señales', 6),
    ('Desarrollo de sistemas de procesamiento digital de señales', 'TE2011B', 6),
    ('TE2011B', 'Diseño de sistemas de comunicaciones', 6),
    ('Diseño de sistemas de comunicaciones', 'TE2012B', 6),
    ('TE2012B', 'Análisis de sistemas energéticos', 6),
    ('Análisis de sistemas energéticos', 'TE3004B', 6),
    ('TE3004B', 'Desarrollo de telecomunicaciones y sistemas energéticos', 6),
    ('Desarrollo de telecomunicaciones y sistemas energéticos', 'F2002B', 6),
    ('F2002B', 'Solución de problemas de mecánica clásica', 6),
    ('Solución de problemas de mecánica clásica', 'F2003B', 6),
    ('F2003B', 'Modelación numérica de sistemas físicos determinísticos', 6),
    ('Modelación numérica de sistemas físicos determinísticos', 'F2004B', 6),
    ('F2004B', 'Aplicación de las fuentes alternas de energía', 6),
    ('Aplicación de las fuentes alternas de energía', 'F2017', 6),
    ('F2017', 'Fundamentación de la electrodinámica', 6),
    ('Fundamentación de la electrodinámica', 'F2005B', 6),
    ('F2005B', 'Análisis de fenómenos ópticos', 6),
    ('Análisis de fenómenos ópticos', 'F2006B', 6),
    ('F2006B', 'Modelación numérica de sistemas estocásticos', 6),
    ('Modelación numérica de sistemas estocásticos', 'F2007B', 6),
    ('F2007B', 'Análisis de los sistemas termodinámicos y estadísticos', 6),
    ('Análisis de los sistemas termodinámicos y estadísticos', 'F2018', 6),
    ('F2018', 'Análisis de sistemas cuánticos', 6),
    ('Análisis de sistemas cuánticos', 'F2008B', 6),
    ('F2008B', 'Caracterización experimental de sistemas ópticos', 6),
    ('Caracterización experimental de sistemas ópticos', 'F2009B', 6),
    ('F2009B', 'Caracterización experimental de materiales', 6),
    ('Caracterización experimental de materiales', 'TE2001B', 6),
    ('TE2001B', 'Caracterización experimental mediante instrumentación electrónica', 6),
    ('Caracterización experimental mediante instrumentación electrónica', 'F3001B', 6),
    ('F3001B', 'Integración de ingeniería física', 6),
    ('Integración de ingeniería física', 'OP1007', 6),
    ('OP1007', 'Optativa de fundamentos en ingeniería', 6),
    ('Optativa de fundamentos en ingeniería', 'NN2001B', 6),
    ('NN2001B', 'Diseño y creación de soluciones innovadoras', 6),
    ('Diseño y creación de soluciones innovadoras', 'NN2007', 6),
    ('NN2007', 'Estudio de metodologías para la innovación', 6),
    ('Estudio de metodologías para la innovación', 'OP2019', 6),
    ('OP2019', 'Optativa de acentuación en ingeniería I', 6),
    ('Optativa de acentuación en ingeniería I', 'OP2026', 6),
    ('OP2026', 'Optativa de acentuación en ingeniería II', 6),
    ('Optativa de acentuación en ingeniería II', 'NN2002B', 6),
    ('NN2002B', 'Diseño y evaluación de emprendimientos tecnológicos', 6),
    ('Diseño y evaluación de emprendimientos tecnológicos', 'NN2008', 6),
    ('NN2008', 'Análisis de factibilidad y viabilidad de proyectos de innovación', 6),
    ('Análisis de factibilidad y viabilidad de proyectos de innovación', 'OP2027', 6),
    ('OP2027', 'Optativa de acentuación en ingeniería III', 6),
    ('Optativa de acentuación en ingeniería III', 'OP2028', 6),
    ('OP2028', 'Optativa de acentuación en ingeniería IV', 6),
    ('Optativa de acentuación en ingeniería IV', 'NN3001B', 6),
    ('NN3001B', 'Gestión estratégica de la innovación tecnológica', 6),
    ('Gestión estratégica de la innovación tecnológica', 'NN3002B', 6),
    ('NN3002B', 'Desarrollo de proyecto integrador de innovación', 6),
    ('Desarrollo de proyecto integrador de innovación', 'SD1001', 6),
    ('SD1001', 'Sistema musculoesquelético', 6),
    ('Sistema musculoesquelético', 'SD1002B', 6),
    ('SD1002B', 'Metabolismo y energía', 6),
    ('Metabolismo y energía', 'SD1003', 6),
    ('SD1003', 'Aporte y consumo de oxígeno', 6),
    ('Aporte y consumo de oxígeno', 'BI2001B', 6),
    ('BI2001B', 'Diseño de sistemas de bioinstrumentación analógica', 6),
    ('Diseño de sistemas de bioinstrumentación analógica', 'BI2002B', 6),
    ('BI2002B', 'Diseño de sistemas de bioinstrumentación digital', 6),
    ('Diseño de sistemas de bioinstrumentación digital', 'BI2003B', 6),
    ('BI2003B', 'Análisis químico, biológico y molecular', 6),
    ('Análisis químico, biológico y molecular', 'BI2010', 6),
    ('BI2010', 'Análisis de señales y sistemas biomédicos', 6),
    ('Análisis de señales y sistemas biomédicos', 'BI2011', 6),
    ('BI2011', 'Aplicación de tecnologías de la información en salud', 6),
    ('Aplicación de tecnologías de la información en salud', 'BI2004B', 6),
    ('BI2004B', 'Análisis y diseño en biomecánica', 6),
    ('Análisis y diseño en biomecánica', 'BI2005B', 6),
    ('BI2005B', 'Aplicación de bioinstrumentación y tecnologías biomédicas', 6),
    ('Aplicación de bioinstrumentación y tecnologías biomédicas', 'BI2006B', 6),
    ('BI2006B', 'Gestión y validación de tecnologías biomédicas', 6),
    ('Gestión y validación de tecnologías biomédicas', 'BI2012', 6),
    ('BI2012', 'Caracterización de biomateriales', 6),
    ('Caracterización de biomateriales', 'BI2013', 6),
    ('BI2013', 'Modelación y control de sistemas biomédicos', 6),
    ('Modelación y control de sistemas biomédicos', 'SD1012', 6),
    ('SD1012', 'Sistema nervioso', 6),
    ('Sistema nervioso', 'BI2007B', 6),
    ('BI2007B', 'Análisis de sistemas de imagenología', 6),
    ('Análisis de sistemas de imagenología', 'BI2008B', 6),
    ('BI2008B', 'Aplicación de la Ingeniería tisular y bioimpresión', 6),
    ('Aplicación de la Ingeniería tisular y bioimpresión', 'BI2009B', 6),
    ('BI2009B', 'Procesamiento de imágenes médicas para el diagnóstico', 6),
    ('Procesamiento de imágenes médicas para el diagnóstico', 'BI2010B', 6),
    ('BI2010B', 'Diseño y desarrollo en neuroingeniería', 6),
    ('Diseño y desarrollo en neuroingeniería', 'BI2011B', 6),
    ('BI2011B', 'Implementación de ingeniería clínica', 6),
    ('Implementación de ingeniería clínica', 'BI2012B', 6),
    ('BI2012B', 'Análisis de la mecánica de biofluidos', 6),
    ('Análisis de la mecánica de biofluidos', 'BI3001B', 6),
    ('BI3001B', 'Desarrollo de dispositivos médicos', 6),
    ('Desarrollo de dispositivos médicos', 'M2002B', 6),
    ('M2002B', 'Diseño de productos sometidos a cargas estáticas', 6),
    ('Diseño de productos sometidos a cargas estáticas', 'M2003B', 6),
    ('M2003B', 'Diseño dinámico', 6),
    ('Diseño dinámico', 'M2033', 6),
    ('M2033', 'Análisis de esfuerzos y deformaciones', 6),
    ('Análisis de esfuerzos y deformaciones', 'M2034', 6),
    ('M2034', 'Análisis del movimiento de cuerpos rígidos', 6),
    ('Análisis del movimiento de cuerpos rígidos', 'M2035', 6),
    ('M2035', 'Fundamentación de ingeniería de materiales', 6),
    ('Fundamentación de ingeniería de materiales', 'M2004B', 6),
    ('M2004B', 'Diseño de mecanismos', 6),
    ('Diseño de mecanismos', 'M2005B', 6),
    ('M2005B', 'Diseño de sistemas termofluídicos', 6),
    ('Diseño de sistemas termofluídicos', 'M2036', 6),
    ('M2036', 'Fundamentación de mecánica de fluidos', 6),
    ('Fundamentación de mecánica de fluidos', 'M2037', 6),
    ('M2037', 'Análisis de los procesos de transformación energética', 6),
    ('Análisis de los procesos de transformación energética', 'M2038', 6),
    ('M2038', 'Modelación de transferencia de calor', 6),
    ('Modelación de transferencia de calor', 'M2006B', 6),
    ('M2006B', 'Diseño de máquinas térmicas', 6),
    ('Diseño de máquinas térmicas', 'M2007B', 6),
    ('M2007B', 'Análisis y prevención de fallas', 6),
    ('Análisis y prevención de fallas', 'M2008B', 6),
    ('M2008B', 'Diseño de elementos de máquinas', 6),
    ('Diseño de elementos de máquinas', 'M3001B', 6),
    ('M3001B', 'Diseño de máquinas', 6),
    ('Diseño de máquinas', 'Q1001B', 6),
    ('Q1001B', 'Fundamentación de las propiedades de nanomateriales y materiales', 6),
    ('Fundamentación de las propiedades de nanomateriales y materiales', 'Q1002B', 6),
    ('Q1002B', 'Obtención de nanomateriales, materiales orgánicos y bioinorgánicos', 6),
    ('Obtención de nanomateriales, materiales orgánicos y bioinorgánicos', 'NT2001B', 6),
    ('NT2001B', 'Fabricación de nanoestructuras por métodos químicos', 6),
    ('Fabricación de nanoestructuras por métodos químicos', 'NT2002B', 6),
    ('NT2002B', 'Fabricación de nano y microestructuras por métodos físicos', 6),
    ('Fabricación de nano y microestructuras por métodos físicos', 'Q2001B', 6),
    ('Q2001B', 'Fundamentación fisicoquímica de las propiedades de las nanoestructuras', 6),
    ('Fundamentación fisicoquímica de las propiedades de las nanoestructuras', 'Q2024', 6),
    ('Q2024', 'Caracterización de materiales y nanomateriales', 6),
    ('Caracterización de materiales y nanomateriales', 'Q2025', 6),
    ('Q2025', 'Fundamentación de química médica y nanomedicina', 6),
    ('Fundamentación de química médica y nanomedicina', 'F2001B', 6),
    ('F2001B', 'Desarrollo de nanosistemas fotónicos', 6),
    ('Desarrollo de nanosistemas fotónicos', 'F2015', 6),
    ('F2015', 'Fundamentación del estado sólido de la materia', 6),
    ('Fundamentación del estado sólido de la materia', 'F2016', 6),
    ('F2016', 'Fundamentación de electromagnetismo', 6),
    ('Fundamentación de electromagnetismo', 'NT2003B', 6),
    ('NT2003B', 'Desarrollo de nanosistemas fluídicos y mecánicos', 6),
    ('Desarrollo de nanosistemas fluídicos y mecánicos', 'Q2002B', 6),
    ('Q2002B', 'Modelación de sistemas moleculares', 6),
    ('Modelación de sistemas moleculares', 'Q2026', 6),
    ('Q2026', 'Formulación de productos nanotecnológicos', 6),
    ('Formulación de productos nanotecnológicos', 'NT2001', 6),
    ('NT2001', 'Diseño de dispositivos nanotecnológicos', 6),
    ('Diseño de dispositivos nanotecnológicos', 'NT2002', 6),
    ('NT2002', 'Generación de prototipos y escalamiento de procesos', 6),
    ('Generación de prototipos y escalamiento de procesos', 'NT2004B', 6),
    ('NT2004B', 'Aplicación de nanodispositivos en soluciones integrales', 6),
    ('Aplicación de nanodispositivos en soluciones integrales', 'NT2005B', 6),
    ('NT2005B', 'Aplicación de prototipado y escalamiento en soluciones integrales', 6),
    ('Aplicación de prototipado y escalamiento en soluciones integrales', 'Q2003B', 6),
    ('Q2003B', 'Aplicación de investigación en soluciones integrales', 6),
    ('Aplicación de investigación en soluciones integrales', 'Q2027', 6),
    ('Q2027', 'Investigación y diseño experimental', 6),
    ('Investigación y diseño experimental', 'Q3001B', 6),
    ('Q3001B', 'Desarrollo de proyectos de nanotecnología', 6),
    ('Desarrollo de proyectos de nanotecnología', 'IQ2007B', 6),
    ('IQ2007B', 'Diseño de sistemas de flujo de fluidos', 6),
    ('Diseño de sistemas de flujo de fluidos', 'IQ2008B', 6),
    ('IQ2008B', 'Diseño de sistemas de transferencia de calor', 6),
    ('Diseño de sistemas de transferencia de calor', 'IQ2009B', 6),
    ('IQ2009B', 'Análisis de procesos de transferencia de calor y flujo de fluidos', 6),
    ('Análisis de procesos de transferencia de calor y flujo de fluidos', 'IQ2015', 6),
    ('IQ2015', 'Modelación de fenómenos de transporte', 6),
    ('Modelación de fenómenos de transporte', 'IQ2010B', 6),
    ('IQ2010B', 'Diseño de procesos de separación', 6),
    ('Diseño de procesos de separación', 'IQ2011B', 6),
    ('IQ2011B', 'Diseño de reactores químicos', 6),
    ('Diseño de reactores químicos', 'IQ2012B', 6),
    ('IQ2012B', 'Análisis de procesos de separación y reacción', 6),
    ('Análisis de procesos de separación y reacción', 'IQ2016', 6),
    ('IQ2016', 'Predicción del equilibrio químico y de fases', 6),
    ('Predicción del equilibrio químico y de fases', 'IQ2013B', 6),
    ('IQ2013B', 'Diseño integral de procesos químicos', 6),
    ('Diseño integral de procesos químicos', 'IQ2017', 6),
    ('IQ2017', 'Diseño de procesos químicos', 6),
    ('Diseño de procesos químicos', 'MR2021', 6),
    ('MR2021', 'Automatización y control de procesos químicos', 6),
    ('Automatización y control de procesos químicos', 'IQ3002B', 6),
    ('IQ3002B', 'Aplicación de la ingeniería de procesos en proyectos industriales', 6),
    ('Aplicación de la ingeniería de procesos en proyectos industriales', 'TE1019', 6),
    ('TE1019', 'Fundamentación de ingeniería eléctrica y electrónica', 6),
    ('Fundamentación de ingeniería eléctrica y electrónica', 'MA2016', 6),
    ('MA2016', 'Modelación matemática avanzada', 6),
    ('Modelación matemática avanzada', 'TE2002B', 6),
    ('TE2002B', 'Diseño con lógica programable', 6),
    ('Diseño con lógica programable', 'TE2003B', 6),
    ('TE2003B', 'Diseño de sistemas en chip', 6),
    ('Diseño de sistemas en chip', 'TE2044', 6),
    ('TE2044', 'Fundamentación electrónica', 6),
    ('Fundamentación electrónica', 'TE2045', 6),
    ('TE2045', 'MR2002B', 6),
    ('MR2002B', 'Análisis de sistemas de control', 6),
    ('Análisis de sistemas de control', 'TC2036', 6),
    ('TC2036', 'Implementación de redes seguras', 6),
    ('Implementación de redes seguras', 'TE2004B', 6),
    ('TE2004B', 'Diseño de sistemas embebidos avanzados', 6),
    ('Diseño de sistemas embebidos avanzados', 'TE3001B', 6),
    ('TE3001B', 'Fundamentación de robótica', 6),
    ('Fundamentación de robótica', 'TE3002B', 6),
    ('TE3002B', 'Implementación de robótica inteligente', 6),
    ('Implementación de robótica inteligente', 'TE3003B', 6),
    ('TE3003B', 'Integración de robótica y sistemas inteligentes', 6),
    ('Integración de robótica y sistemas inteligentes', 'TC2005B', 6),
    ('TC2005B', 'Construcción de software y toma de decisiones', 6),
    ('Construcción de software y toma de decisiones', 'TC2006B', 6),
    ('TC2006B', 'Interconexión de dispositivos', 6),
    ('Interconexión de dispositivos', 'TC2037', 6),
    ('TC2037', 'Implementación de métodos computacionales', 6),
    ('Implementación de métodos computacionales', 'TC2007B', 6),
    ('TC2007B', 'Integración de seguridad informática en redes y sistemas de software', 6),
    ('Integración de seguridad informática en redes y sistemas de software', 'TC2008B', 6),
    ('TC2008B', 'Modelación de sistemas multiagentes con gráficas computacionales', 6),
    ('Modelación de sistemas multiagentes con gráficas computacionales', 'TC2038', 6),
    ('TC2038', 'Análisis y diseño de algoritmos avanzados', 6),
    ('Análisis y diseño de algoritmos avanzados', 'TC3001B', 6),
    ('TC3001B', 'Desarrollo de software', 6),
    ('Desarrollo de software', 'TC3002B', 6),
    ('TC3002B', 'Desarrollo de aplicaciones avanzadas de ciencias computacionales', 6),
    ('Desarrollo de aplicaciones avanzadas de ciencias computacionales', 'TC3003B', 6),
    ('TC3003B', 'Implementación de redes de área amplia y servicios distribuidos', 6),
    ('Implementación de redes de área amplia y servicios distribuidos', 'AD2029', 6),
    ('AD2029', 'Modelación, estructura y operación de los negocios', 6),
    ('Modelación, estructura y operación de los negocios', 'TI2002B', 6),
    ('TI2002B', 'Evaluación de arquitecturas empresariales', 6),
    ('Evaluación de arquitecturas empresariales', 'TI2003B', 6),
    ('TI2003B', 'Evaluación de tecnología para los negocios', 6),
    ('Evaluación de tecnología para los negocios', 'TI2004B', 6),
    ('TI2004B', 'Exploración e interpretación de datos', 6),
    ('Exploración e interpretación de datos', 'TI2018', 6),
    ('TI2018', 'Diseño de arquitecturas, uso y administración de datos', 6),
    ('Diseño de arquitecturas, uso y administración de datos', 'TI2019', 6),
    ('TI2019', 'Evaluación y administración de proyectos', 6),
    ('Evaluación y administración de proyectos', 'AD2008B', 6),
    ('AD2008B', 'Administración del cambio', 6),
    ('Administración del cambio', 'AD2030', 6),
    ('AD2030', 'Análisis del comportamiento y desempeño organizacional', 6),
    ('Análisis del comportamiento y desempeño organizacional', 'FZ2025', 6),
    ('FZ2025', 'Análisis de las actividades económicas', 6),
    ('Análisis de las actividades económicas', 'TI2005B', 6),
    ('TI2005B', 'Diseño de procesos y arquitecturas empresariales', 6),
    ('Diseño de procesos y arquitecturas empresariales', 'TI2006B', 6),
    ('TI2006B', 'Soporte analítico para la toma de decisiones', 6),
    ('Soporte analítico para la toma de decisiones', 'TI2020', 6),
    ('TI2020', 'Implementación de tecnología en los procesos', 6),
    ('Implementación de tecnología en los procesos', 'TI3001B', 6),
    ('TI3001B', 'Administración estratégica y gobierno de tecnologías de información', 6),
    ('Administración estratégica y gobierno de tecnologías de información', 'TI3002B', 6),
    ('TI3002B', 'Innovación y diseño de iniciativas de transformación digital', 6),
    ('Innovación y diseño de iniciativas de transformación digital', 'TI3003B', 6),
    ('TI3003B', 'Aplicación de analítica y gobierno de datos', 6),
    ('Aplicación de analítica y gobierno de datos', 'TI3004B', 6),
    ('TI3004B', 'Transformación digital de la organización', 6),
    ('Transformación digital de la organización', 'A2001B', 6),
    ('A2001B', 'Pre-producción de cortometraje animado', 6),
    ('Pre-producción de cortometraje animado', 'A2002B', 6),
    ('A2002B', 'Producción de cortometraje animado', 6),
    ('Producción de cortometraje animado', 'A2012', 6),
    ('A2012', 'Dibujo', 6),
    ('Dibujo', 'A2013', 6),
    ('A2013', 'Historia de la animación', 6),
    ('Historia de la animación', 'A2014', 6),
    ('A2014', 'Fundamentos de la animación', 6),
    ('Fundamentos de la animación', 'A2003B', 6),
    ('A2003B', 'Arte conceptual', 6),
    ('Arte conceptual', 'A2004B', 6),
    ('A2004B', 'Fundamentos de interacción', 6),
    ('Fundamentos de interacción', 'A2005B', 6),
    ('A2005B', 'Arte instalación', 6),
    ('Arte instalación', 'A2015', 6),
    ('A2015', 'Exploración de la forma', 6),
    ('Exploración de la forma', 'A2016', 6),
    ('A2016', 'Introducción al 3D', 6),
    ('Introducción al 3D', 'OP3070', 6),
    ('OP3070', 'Optativa de arte digital I', 6),
    ('Optativa de arte digital I', 'OP3071', 6),
    ('OP3071', 'Optativa de arte digital II', 6),
    ('Optativa de arte digital II', 'OP3072', 6),
    ('OP3072', 'Optativa de arte digital III', 6),
    ('Optativa de arte digital III', 'OP3073', 6),
    ('OP3073', 'Optativa de arte digital IV', 6),
    ('Optativa de arte digital IV', 'OP3074', 6),
    ('OP3074', 'Optativa de arte digital V', 6),
    ('Optativa de arte digital V', 'OP3075', 6),
    ('OP3075', 'Optativa de arte digital VI', 6),
    ('Optativa de arte digital VI', 'AT3001B', 6),
    ('AT3001B', 'Proyecto de arte digital', 6),
    ('Proyecto de arte digital', 'AT3002B', 6),
    ('AT3002B', 'Proyecto integral de arte digital', 6),
    ('Proyecto integral de arte digital', 'AD2001B', 6),
    ('AD2001B', 'Detección de oportunidades estratégicas', 6),
    ('Detección de oportunidades estratégicas', 'AD2002B', 6),
    ('AD2002B', 'Diseño de organizaciones flexibles', 6),
    ('Diseño de organizaciones flexibles', 'AD2004B', 6),
    ('AD2004B', 'Liderazgo para la transformación', 6),
    ('Liderazgo para la transformación', 'AD2025', 6),
    ('AD2025', 'Pensamiento estratégico', 6),
    ('Pensamiento estratégico', 'AD2005B', 6),
    ('AD2005B', 'Aseguramiento de la co-creación de valor', 6),
    ('Aseguramiento de la co-creación de valor', 'AD2006B', 6),
    ('AD2006B', 'Diseño estratégico para crear valor', 6),
    ('Diseño estratégico para crear valor', 'AD2026', 6),
    ('AD2026', 'Construcción de habilidades interpersonales', 6),
    ('Construcción de habilidades interpersonales', 'AD2027', 6),
    ('AD2027', 'Innovación y co-creación de valor', 6),
    ('Innovación y co-creación de valor', 'AD3001B', 6),
    ('AD3001B', 'Gestión estratégica de PYMES', 6),
    ('Gestión estratégica de PYMES', 'AD3002B', 6),
    ('AD3002B', 'Institucionalización de la empresa familiar', 6),
    ('Institucionalización de la empresa familiar', 'FZ2001B', 6),
    ('FZ2001B', 'Análisis de inversiones', 6),
    ('Análisis de inversiones', 'FZ2002B', 6),
    ('FZ2002B', 'Cultura financiera', 6),
    ('Cultura financiera', 'FZ2004B', 6),
    ('FZ2004B', 'Gestión de tesorería', 6),
    ('Gestión de tesorería', 'FZ2019', 6),
    ('FZ2019', 'Modelos econométricos', 6),
    ('Modelos econométricos', 'FZ2020', 6),
    ('FZ2020', 'Series de tiempo', 6),
    ('Series de tiempo', 'FZ2021', 6),
    ('FZ2021', 'Teoría de inversiones', 6),
    ('Teoría de inversiones', 'FZ2005B', 6),
    ('FZ2005B', 'Análisis de financiamiento', 6),
    ('Análisis de financiamiento', 'FZ2008B', 6),
    ('FZ2008B', 'Valuación de empresas', 6),
    ('Valuación de empresas', 'FZ2009B', 6),
    ('FZ2009B', 'Vehículos de inversión y cobertura', 6),
    ('Vehículos de inversión y cobertura', 'FZ2022', 6),
    ('FZ2022', 'Algoritmos y análisis de datos', 6),
    ('Algoritmos y análisis de datos', 'FZ2023', 6),
    ('FZ2023', 'Instrumentos derivados', 6),
    ('Instrumentos derivados', 'FZ2024', 6),
    ('FZ2024', 'Modelación y programación financiera', 6),
    ('Modelación y programación financiera', 'FZ3001B', 6),
    ('FZ3001B', 'Administración financiera internacional', 6),
    ('Administración financiera internacional', 'FZ3002B', 6),
    ('FZ3002B', 'Gestión de fondos de inversión', 6),
    ('Gestión de fondos de inversión', 'CF2001B', 6),
    ('CF2001B', 'Diagnóstico financiero', 6),
    ('Diagnóstico financiero', 'CF2002B', 6),
    ('CF2002B', 'Integración financiera de procesos de negocio', 6),
    ('Integración financiera de procesos de negocio', 'CF2022', 6),
    ('CF2022', 'Cumplimiento fiscal', 6),
    ('Cumplimiento fiscal', 'CF2023', 6),
    ('CF2023', 'Optimización de costos', 6),
    ('Optimización de costos', 'FZ2003B', 6),
    ('FZ2003B', 'Decisiones de negocio estratégicas', 6),
    ('Decisiones de negocio estratégicas', 'TI2016', 6),
    ('TI2016', 'Estructuras de información', 6),
    ('Estructuras de información', 'CF2003B', 6),
    ('CF2003B', 'Desarrollo de arquitectura contable', 6),
    ('Desarrollo de arquitectura contable', 'CF2024', 6),
    ('CF2024', 'Diseño de estrategia financiera', 6),
    ('Diseño de estrategia financiera', 'CF2025', 6),
    ('CF2025', 'Valuación y presentación de financiamientos', 6),
    ('Valuación y presentación de financiamientos', 'CF2026', 6),
    ('CF2026', 'Valuación y presentación de inversiones', 6),
    ('Valuación y presentación de inversiones', 'FZ2006B', 6),
    ('FZ2006B', 'Análisis fundamental de empresas', 6),
    ('Análisis fundamental de empresas', 'FZ2007B', 6),
    ('FZ2007B', 'Creación de valor corporativo', 6),
    ('Creación de valor corporativo', 'Séptimo Semestre', 6),
    ('CF3001B', 'Formación de juicio crítico profesional', 7),
    ('Formación de juicio crítico profesional', 'CF3024', 7),
    ('CF3024', 'Aseguramiento e interés público', 7),
    ('Aseguramiento e interés público', 'CF3026', 7),
    ('CF3026', 'Ciclo tributario y empresas', 7),
    ('Ciclo tributario y empresas', 'CF3027', 7),
    ('CF3027', 'Consolidación de información financiera', 7),
    ('Consolidación de información financiera', 'CF3002B', 7),
    ('CF3002B', 'Dirección financiera y contraloría estratégica', 7),
    ('Dirección financiera y contraloría estratégica', 'AV2001B', 7),
    ('AV2001B', 'Producción de audio, video y diseño digital', 7),
    ('Producción de audio, video y diseño digital', 'CO2001B', 7),
    ('CO2001B', 'Metodologías de investigación para la comunicación', 7),
    ('Metodologías de investigación para la comunicación', 'CO2011', 7),
    ('CO2011', 'Teorías de la comunicación', 7),
    ('Teorías de la comunicación', 'EH2006', 7),
    ('EH2006', 'Del humanismo al post-humanismo', 7),
    ('Del humanismo al post-humanismo', 'AV2002B', 7),
    ('AV2002B', 'Guionismo y producción de narrativas audiovisuales', 7),
    ('Guionismo y producción de narrativas audiovisuales', 'AV2016', 7),
    ('AV2016', 'Fotografía publicitaria y comercial', 7),
    ('Fotografía publicitaria y comercial', 'CR2001B', 7),
    ('CR2001B', 'Comunicación estratégica aplicada', 7),
    ('Comunicación estratégica aplicada', 'AV2003B', 7),
    ('AV2003B', 'Narrativa documental', 7),
    ('Narrativa documental', 'CO2002B', 7),
    ('CO2002B', 'Comunicación, mercadotecnia digital y minería de datos', 7),
    ('Comunicación, mercadotecnia digital y minería de datos', 'CO2012', 7),
    ('CO2012', 'Estudios culturales y medios', 7),
    ('Estudios culturales y medios', 'MI2003B', 7),
    ('MI2003B', 'Producción periodística convergente', 7),
    ('Producción periodística convergente', 'CO3001B', 7),
    ('CO3001B', 'Proyecto integrador de comunicación', 7),
    ('Proyecto integrador de comunicación', 'EM2001B', 7),
    ('EM2001B', 'Adaptación de oportunidad y solución', 7),
    ('Adaptación de oportunidad y solución', 'EM2002B', 7),
    ('EM2002B', 'Evaluación y comunicación de oportunidades', 7),
    ('Evaluación y comunicación de oportunidades', 'EM2003B', 7),
    ('EM2003B', 'Exploración de alto impacto', 7),
    ('Exploración de alto impacto', 'EM2013', 7),
    ('EM2013', 'Innovación en la cadena de valor', 7),
    ('Innovación en la cadena de valor', 'EM2014', 7),
    ('EM2014', 'Liderazgo emprendedor', 7),
    ('Liderazgo emprendedor', 'EM2015', 7),
    ('EM2015', 'Oportunidades de emprendimiento corporativo', 7),
    ('Oportunidades de emprendimiento corporativo', 'EM2004B', 7),
    ('EM2004B', 'Diseño de prototipos', 7),
    ('Diseño de prototipos', 'EM2005B', 7),
    ('EM2005B', 'Diseño de soluciones de alto impacto', 7),
    ('Diseño de soluciones de alto impacto', 'EM2006B', 7),
    ('EM2006B', 'Generación y validación de prototipos', 7),
    ('Generación y validación de prototipos', 'EM2016', 7),
    ('EM2016', 'Metodologías de innovación', 7),
    ('Metodologías de innovación', 'EM2017', 7),
    ('EM2017', 'Metodologías de innovación tecnológica', 7),
    ('Metodologías de innovación tecnológica', 'EM2018', 7),
    ('EM2018', 'Técnicas de prototipaje', 7),
    ('Técnicas de prototipaje', 'EM3001B', 7),
    ('EM3001B', 'Escalabilidad', 7),
    ('Escalabilidad', 'EM3002B', 7),
    ('EM3002B', 'Persuasión y ventas', 7),
    ('Persuasión y ventas', 'DL2001B', 7),
    ('DL2001B', 'Comunicación digital del producto', 7),
    ('Comunicación digital del producto', 'DL2002B', 7),
    ('DL2002B', 'Configuración del objeto', 7),
    ('Configuración del objeto', 'DL2042', 7),
    ('DL2042', 'Representación visual', 7),
    ('Representación visual', 'DL2043', 7),
    ('DL2043', 'Materia y expresión', 7),
    ('Materia y expresión', 'DL2003B', 7),
    ('DL2003B', 'Pensamiento y proceso creativo', 7),
    ('Pensamiento y proceso creativo', 'DL2004B', 7),
    ('DL2004B', 'Especificación de productos y servicios', 7),
    ('Especificación de productos y servicios', 'DL2005B', 7),
    ('DL2005B', 'Diseño e innovación', 7),
    ('Diseño e innovación', 'DL2044', 7),
    ('DL2044', 'Administración de proyectos de diseño', 7),
    ('Administración de proyectos de diseño', 'OP3076', 7),
    ('OP3076', 'Optativa de diseño I', 7),
    ('Optativa de diseño I', 'OP3077', 7),
    ('OP3077', 'Optativa de diseño II', 7),
    ('Optativa de diseño II', 'OP3078', 7),
    ('OP3078', 'Optativa de diseño III', 7),
    ('Optativa de diseño III', 'OP3079', 7),
    ('OP3079', 'Optativa de diseño IV', 7),
    ('Optativa de diseño IV', 'OP3080', 7),
    ('OP3080', 'Optativa de diseño V', 7),
    ('Optativa de diseño V', 'OP3081', 7),
    ('OP3081', 'Optativa de diseño VI', 7),
    ('Optativa de diseño VI', 'DL3001B', 7),
    ('DL3001B', 'Proyecto de diseño', 7),
    ('Proyecto de diseño', 'DL3002B', 7),
    ('DL3002B', 'Proyecto integral de diseño', 7),
    ('Proyecto integral de diseño', 'RH2001B', 7),
    ('RH2001B', 'Estrategias para potenciar el talento humano', 7),
    ('Estrategias para potenciar el talento humano', 'RH2002B', 7),
    ('RH2002B', 'Planeación del capital humano', 7),
    ('Planeación del capital humano', 'RH2003B', 7),
    ('RH2003B', 'Valoración estratégica del trabajo', 7),
    ('Valoración estratégica del trabajo', 'RH2012', 7),
    ('RH2012', 'Atracción y desarrollo del talento en entornos digitales', 7),
    ('Atracción y desarrollo del talento en entornos digitales', 'RH2013', 7),
    ('RH2013', 'Desempeño y retribución en contextos globales', 7),
    ('Desempeño y retribución en contextos globales', 'TI2015', 7),
    ('TI2015', 'Analítica del talento', 7),
    ('Analítica del talento', 'AD2028', 7),
    ('AD2028', 'Responsabilidad social y talento humano', 7),
    ('Responsabilidad social y talento humano', 'RH2004B', 7),
    ('RH2004B', 'Comprensión del ambiente laboral', 7),
    ('Comprensión del ambiente laboral', 'RH2005B', 7),
    ('RH2005B', 'Creación de valor desde el talento', 7),
    ('Creación de valor desde el talento', 'RH2006B', 7),
    ('RH2006B', 'Diseño de experiencias laborales plenas', 7),
    ('Diseño de experiencias laborales plenas', 'RH2014', 7),
    ('RH2014', 'Organizaciones positivas', 7),
    ('Organizaciones positivas', 'RH2015', 7),
    ('RH2015', 'Versatilidad organizacional', 7),
    ('Versatilidad organizacional', 'RH3001B', 7),
    ('RH3001B', 'Liderazgo estratégico del talento', 7),
    ('Liderazgo estratégico del talento', 'RH3002B', 7),
    ('RH3002B', 'Potenciación de la cultura organizacional', 7),
    ('Potenciación de la cultura organizacional', 'EC2001B', 7),
    ('EC2001B', 'Dinero y capitales', 7),
    ('Dinero y capitales', 'EC2003B', 7),
    ('EC2003B', 'Incentivos del consumidor y productor', 7),
    ('Incentivos del consumidor y productor', 'EC2004B', 7),
    ('EC2004B', 'Origen y futuro del panorama macroeconómico', 7),
    ('Origen y futuro del panorama macroeconómico', 'EC2029', 7),
    ('EC2029', 'Fundamentos de econometría', 7),
    ('Fundamentos de econometría', 'MA2012', 7),
    ('MA2012', 'Fundamentos de estadística', 7),
    ('Fundamentos de estadística', 'MA2013', 7),
    ('MA2013', 'Pensamiento matemático IV', 7),
    ('Pensamiento matemático IV', 'EC2005B', 7),
    ('EC2005B', 'Competencia económica', 7),
    ('Competencia económica', 'EC2006B', 7),
    ('EC2006B', 'Decisiones estratégicas en mercados e instituciones', 7),
    ('Decisiones estratégicas en mercados e instituciones', 'EC2007B', 7),
    ('EC2007B', 'Dinámica del crecimiento nacional y regional', 7),
    ('Dinámica del crecimiento nacional y regional', 'EC2030', 7),
    ('EC2030', 'Econometría I', 7),
    ('Econometría I', 'EC2031', 7),
    ('EC2031', 'Econometría II', 7),
    ('Econometría II', 'EC2032', 7),
    ('EC2032', 'Multivariante', 7),
    ('Multivariante', 'EC3002B', 7),
    ('EC3002B', 'Solución y evaluación de problemas económicos', 7),
    ('Solución y evaluación de problemas económicos', 'D2001B', 7),
    ('D2001B', 'Bienes y derechos reales', 7),
    ('Bienes y derechos reales', 'D2002B', 7),
    ('D2002B', 'Derecho constitucional', 7),
    ('Derecho constitucional', 'D2031', 7),
    ('D2031', 'Argumentación jurídica', 7),
    ('Argumentación jurídica', 'D2032', 7),
    ('D2032', 'Personas y acto jurídico', 7),
    ('Personas y acto jurídico', 'D2033', 7),
    ('D2033', 'Seminario de argumentación jurídica', 7),
    ('Seminario de argumentación jurídica', 'D2034', 7),
    ('D2034', 'Seminario de personas y acto jurídico', 7),
    ('Seminario de personas y acto jurídico', 'D2035', 7),
    ('D2035', 'Seminario de teoría del derecho', 7),
    ('Seminario de teoría del derecho', 'D2036', 7),
    ('D2036', 'Teoría del derecho', 7),
    ('Teoría del derecho', 'D2003B', 7),
    ('D2003B', 'Derecho penal y delitos en especial', 7),
    ('Derecho penal y delitos en especial', 'D2004B', 7),
    ('D2004B', 'Derechos humanos y su interpretación judicial', 7),
    ('Derechos humanos y su interpretación judicial', 'D2005B', 7),
    ('D2005B', 'Solución de conflictos y teoría general del proceso', 7),
    ('Solución de conflictos y teoría general del proceso', 'D2037', 7),
    ('D2037', 'Derecho de las obligaciones I', 7),
    ('Derecho de las obligaciones I', 'D2038', 7),
    ('D2038', 'Derecho de las obligaciones II', 7),
    ('Derecho de las obligaciones II', 'D2039', 7),
    ('D2039', 'Seminario de derecho de las obligaciones I', 7),
    ('Seminario de derecho de las obligaciones I', 'D2006B', 7),
    ('D2006B', 'Contratos civiles y mercantiles', 7),
    ('Contratos civiles y mercantiles', 'D2007B', 7),
    ('D2007B', 'Derecho administrativo I', 7),
    ('Derecho administrativo I', 'D2008B', 7),
    ('D2008B', 'Familia y sucesiones', 7),
    ('Familia y sucesiones', 'D2040', 7),
    ('D2040', 'Derecho laboral I', 7),
    ('Derecho laboral I', 'D2041', 7),
    ('D2041', 'Derecho laboral ll', 7),
    ('Derecho laboral ll', 'D2042', 7),
    ('D2042', 'Seminario de derecho de las obligaciones II', 7),
    ('Seminario de derecho de las obligaciones II', 'D3001B', 7),
    ('D3001B', 'Controles constitucionales I', 7),
    ('Controles constitucionales I', 'D3002B', 7),
    ('D3002B', 'Derecho administrativo II', 7),
    ('Derecho administrativo II', 'D3003B', 7),
    ('D3003B', 'Derecho procesal civil y mercantil', 7),
    ('Derecho procesal civil y mercantil', 'D3039', 7),
    ('D3039', 'Derecho fiscal', 7),
    ('Derecho fiscal', 'D3040', 7),
    ('D3040', 'Derecho procesal laboral', 7),
    ('Derecho procesal laboral', 'D3041', 7),
    ('D3041', 'Empresa y cumplimiento regulatorio', 7),
    ('Empresa y cumplimiento regulatorio', 'D3042', 7),
    ('D3042', 'Juicios orales', 7),
    ('Juicios orales', 'D3043', 7),
    ('D3043', 'Sistema penal acusatorio', 7),
    ('Sistema penal acusatorio', 'D3044', 7),
    ('D3044', 'Sociedades mercantiles', 7),
    ('Sociedades mercantiles', 'D3004B', 7),
    ('D3004B', 'Controles constitucionales II', 7),
    ('Controles constitucionales II', 'D3005B', 7),
    ('D3005B', 'Derecho internacional privado y arbitraje comercial internacional', 7),
    ('Derecho internacional privado y arbitraje comercial internacional', 'D3006B', 7),
    ('D3006B', 'Derecho procesal fiscal y administrativo', 7),
    ('Derecho procesal fiscal y administrativo', 'D3045', 7),
    ('D3045', 'Derecho de la propiedad intelectual', 7),
    ('Derecho de la propiedad intelectual', 'D3046', 7),
    ('D3046', 'Derecho internacional público', 7),
    ('Derecho internacional público', 'D3047', 7),
    ('D3047', 'Ética para abogados', 7),
    ('Ética para abogados', 'D3048', 7),
    ('D3048', 'Inglés legal', 7),
    ('Inglés legal', 'D3049', 7),
    ('D3049', 'Seminario de derecho internacional público', 7),
    ('Seminario de derecho internacional público', 'D3050', 7),
    ('D3050', 'Títulos y operaciones de crédito', 7),
    ('Títulos y operaciones de crédito', 'Octavo Semestre', 7),
    ('D3007B', 'Investigación jurídica aplicada', 9),
    ('Investigación jurídica aplicada', 'ED2001', 9),
    ('ED2001', 'Fundamentos de la pedagogía', 9),
    ('Fundamentos de la pedagogía', 'ED2001B', 9),
    ('ED2001B', 'Análisis de problemáticas educativas', 9),
    ('Análisis de problemáticas educativas', 'ED2002', 9),
    ('ED2002', 'Metodologías de la investigación educativa', 9),
    ('Metodologías de la investigación educativa', 'ED2002B', 9),
    ('ED2002B', 'Fundamentación pedagógica aplicada a las soluciones de aprendizaje', 9),
    ('Fundamentación pedagógica aplicada a las soluciones de aprendizaje', 'ED2003', 9),
    ('ED2003', 'Introducción a la administración educativa', 9),
    ('Introducción a la administración educativa', 'ED2003B', 9),
    ('ED2003B', 'Desarrollo de proyectos educativos basados en tecnología', 9),
    ('Desarrollo de proyectos educativos basados en tecnología', 'ED2004B', 9),
    ('ED2004B', 'Exploración de tendencias tecnológicas en educación', 9),
    ('Exploración de tendencias tecnológicas en educación', 'ED2005B', 9),
    ('ED2005B', 'Uso de tecnología en la investigación educativa', 9),
    ('Uso de tecnología en la investigación educativa', 'ED2004', 9),
    ('ED2004', 'Educación global y comparada', 9),
    ('Educación global y comparada', 'ED2006B', 9),
    ('ED2006B', 'Diseño de soluciones para retos educativos', 9),
    ('Diseño de soluciones para retos educativos', 'ED2007B', 9),
    ('ED2007B', 'Desarrollo de proyectos en el marco de las políticas educativas vigentes', 9),
    ('Desarrollo de proyectos en el marco de las políticas educativas vigentes', 'ED3001B', 9),
    ('ED3001B', 'Proyecto integrador de innovación educativa', 9),
    ('Proyecto integrador de innovación educativa', 'MT2001B', 9),
    ('MT2001B', 'Inteligencia de mercado para la generación de conocimiento del consumidor', 9),
    ('Inteligencia de mercado para la generación de conocimiento del consumidor', 'MT2002B', 9),
    ('MT2002B', 'Inteligencia exploratoria de mercados', 9),
    ('Inteligencia exploratoria de mercados', 'MT2003B', 9),
    ('MT2003B', 'Segmentación y posicionamiento de estrategias de valor', 9),
    ('Segmentación y posicionamiento de estrategias de valor', 'MT2027', 9),
    ('MT2027', 'Definición competitiva de mercado', 9),
    ('Definición competitiva de mercado', 'MT2028', 9),
    ('MT2028', 'Diseño de métricas de mercadotecnia', 9),
    ('Diseño de métricas de mercadotecnia', 'MT2029', 9),
    ('MT2029', 'Visión holística del consumidor', 9),
    ('Visión holística del consumidor', 'MT2004B', 9),
    ('MT2004B', 'Desarrollo de marcas que transforman', 9),
    ('Desarrollo de marcas que transforman', 'MT2005B', 9),
    ('MT2005B', 'Diseño de experiencias omnicanal', 9),
    ('Diseño de experiencias omnicanal', 'MT2006B', 9),
    ('MT2006B', 'Gestión sustentable de proyectos de mercadotecnia', 9),
    ('Gestión sustentable de proyectos de mercadotecnia', 'MT2030', 9),
    ('MT2030', 'Diseño de estrategias de mercadotecnia interna', 9),
    ('Diseño de estrategias de mercadotecnia interna', 'MT2031', 9),
    ('MT2031', 'Optimización de precios y cadenas de valor', 9),
    ('Optimización de precios y cadenas de valor', 'MT3001B', 9),
    ('MT3001B', 'Liderazgo de mercadotecnia I', 9),
    ('Liderazgo de mercadotecnia I', 'MT3002B', 9),
    ('MT3002B', 'Liderazgo de mercadotecnia II', 9),
    ('Liderazgo de mercadotecnia II', 'AD2003B', 9),
    ('AD2003B', 'Indicadores y riesgos con visión estratégica', 9),
    ('Indicadores y riesgos con visión estratégica', 'CD2001B', 9),
    ('CD2001B', 'Diagnóstico para líneas de acción', 9),
    ('Diagnóstico para líneas de acción', 'CD2008', 9),
    ('CD2008', 'Análisis descriptivo', 9),
    ('Análisis descriptivo', 'CD2009', 9),
    ('CD2009', 'Manipulación de datos', 9),
    ('Manipulación de datos', 'TI2017', 9),
    ('TI2017', 'Integración de base de datos', 9),
    ('Integración de base de datos', 'AD2007B', 9),
    ('AD2007B', 'Líneas de acción estratégicas', 9),
    ('Líneas de acción estratégicas', 'CD2010', 9),
    ('CD2010', 'Introducción a la econometría', 9),
    ('Introducción a la econometría', 'CD2011', 9),
    ('CD2011', 'Minería de datos', 9),
    ('Minería de datos', 'TC2003B', 9),
    ('TC2003B', 'Gestión de proyectos de plataformas tecnológicas', 9),
    ('Gestión de proyectos de plataformas tecnológicas', 'TI2001B', 9),
    ('TI2001B', 'Plataformas de analítica de negocios para organizaciones', 9),
    ('Plataformas de analítica de negocios para organizaciones', 'AD3003B', 9),
    ('AD3003B', 'Planeación estratégica basada en analítica prescriptiva', 9),
    ('Planeación estratégica basada en analítica prescriptiva', 'H2001B', 9),
    ('H2001B', 'Análisis del discurso', 9),
    ('Análisis del discurso', 'H2002B', 9),
    ('H2002B', 'Textos clásicos', 9),
    ('Textos clásicos', 'H2050', 9),
    ('H2050', 'Análisis crítico de textos', 9),
    ('Análisis crítico de textos', 'H2051', 9),
    ('H2051', 'Estructuras y análisis del español', 9),
    ('Estructuras y análisis del español', 'H2003B', 9),
    ('H2003B', 'Literatura de los Siglos de Oro', 9),
    ('Literatura de los Siglos de Oro', 'H2004B', 9),
    ('H2004B', 'Literatura española medieval', 9),
    ('Literatura española medieval', 'H2005B', 9),
    ('H2005B', 'Literatura novohispana', 9),
    ('Literatura novohispana', 'H2052', 9),
    ('H2052', 'Teoría literaria', 9),
    ('Teoría literaria', 'H2006B', 9),
    ('H2006B', 'Narrativa Iberoamericana de los siglos XIX y XX', 9),
    ('Narrativa Iberoamericana de los siglos XIX y XX', 'H2007B', 9),
    ('H2007B', 'Poesía Iberoamericana de los siglos XIX y XX', 9),
    ('Poesía Iberoamericana de los siglos XIX y XX', 'H2008B', 9),
    ('H2008B', 'Teatro y ensayo iberoamericanos de los siglos XIX y XX', 9),
    ('Teatro y ensayo iberoamericanos de los siglos XIX y XX', 'H2053', 9),
    ('H2053', 'Desarrollo de modelos y prototipos editoriales', 9),
    ('Desarrollo de modelos y prototipos editoriales', 'H3001B', 9),
    ('H3001B', 'Proyecto integrador de letras', 9),
    ('Proyecto integrador de letras', 'MI2001B', 9),
    ('MI2001B', 'Metodologías de la investigación periodística', 9),
    ('Metodologías de la investigación periodística', 'SO2001', 9),
    ('SO2001', 'Estudios sociales y políticos', 9),
    ('Estudios sociales y políticos', 'MI2002B', 9),
    ('MI2002B', 'Producción de contenidos noticiosos', 9),
    ('Producción de contenidos noticiosos', 'MI2007', 9),
    ('MI2007', 'Ejercicio periodístico, derecho a la información y opinión pública', 9),
    ('Ejercicio periodístico, derecho a la información y opinión pública', 'RI2001B', 9),
    ('RI2001B', 'Análisis histórico del sistema internacional', 9),
    ('Análisis histórico del sistema internacional', 'AV2004B', 9),
    ('AV2004B', 'Producción de narrativas convergentes multimodales', 9),
    ('Producción de narrativas convergentes multimodales', 'MI2008', 9),
    ('MI2008', 'Fundamentos del periodismo hipermedia y transmedia', 9),
    ('Fundamentos del periodismo hipermedia y transmedia', 'MI3001B', 9),
    ('MI3001B', 'Proyecto integrador de periodismo', 9),
    ('Proyecto integrador de periodismo', 'RI2002B', 9),
    ('RI2002B', 'Escenarios regionales en el mundo contemporáneo', 9),
    ('Escenarios regionales en el mundo contemporáneo', 'RI2003B', 9),
    ('RI2003B', 'Prospectiva sobre escenarios político-económicos internacionales', 9),
    ('Prospectiva sobre escenarios político-económicos internacionales', 'RI2039', 9),
    ('RI2039', 'Teorías clásicas de relaciones internacionales', 9),
    ('Teorías clásicas de relaciones internacionales', 'RI2040', 9),
    ('RI2040', 'Teorías contemporáneas de relaciones internacionales', 9),
    ('Teorías contemporáneas de relaciones internacionales', 'RI2004B', 9),
    ('RI2004B', 'Conflicto y negociación', 9),
    ('Conflicto y negociación', 'RI2005B', 9),
    ('RI2005B', 'Cooperación y gobernanza global', 9),
    ('Cooperación y gobernanza global', 'RI2006B', 9),
    ('RI2006B', 'Gestión de bienes públicos globales en la sociedad de riesgo', 9),
    ('Gestión de bienes públicos globales en la sociedad de riesgo', 'RI2041', 9),
    ('RI2041', 'Aspectos jurídicos de las relaciones internacionales', 9),
    ('Aspectos jurídicos de las relaciones internacionales', 'RI2042', 9),
    ('RI2042', 'Organismos internacionales', 9),
    ('Organismos internacionales', 'RI2043', 9),
    ('RI2043', 'Riesgos y amenazas en la agenda global contemporánea', 9),
    ('Riesgos y amenazas en la agenda global contemporánea', 'RI3002B', 9),
    ('RI3002B', 'Análisis y estrategias de política exterior', 9),
    ('Análisis y estrategias de política exterior', 'F2010B', 9),
    ('F2010B', 'Fundamentos de la acústica', 9),
    ('Fundamentos de la acústica', 'TM2001', 9),
    ('TM2001', 'Teoría y estilos musicales', 9),
    ('Teoría y estilos musicales', 'TM2001B', 9),
    ('TM2001B', 'Entrenamiento auditivo e instrumental', 9),
    ('Entrenamiento auditivo e instrumental', 'TM2002', 9),
    ('TM2002', 'Negocios en la industria de la música', 9),
    ('Negocios en la industria de la música', 'TM2002B', 9),
    ('TM2002B', 'Aplicación de tecnología en la producción sonora', 9),
    ('Aplicación de tecnología en la producción sonora', 'TM2003', 9),
    ('TM2003', 'Producción sonora y mezcla digital', 9),
    ('Producción sonora y mezcla digital', 'TM2003B', 9),
    ('TM2003B', 'Técnicas de grabación sonora', 9),
    ('Técnicas de grabación sonora', 'TM2004B', 9),
    ('TM2004B', 'Proyecto de producción musical', 9),
    ('Proyecto de producción musical', 'TM2004', 9),
    ('TM2004', 'Postproducción de audio para cine y video', 9),
    ('Postproducción de audio para cine y video', 'TM2005B', 9),
    ('TM2005B', 'Diseño de aplicaciones interactivas de tecnología musical', 9),
    ('Diseño de aplicaciones interactivas de tecnología musical', 'TM2006B', 9),
    ('TM2006B', 'Musicalización de productos audiovisuales', 9),
    ('Musicalización de productos audiovisuales', 'TM2007B', 9),
    ('TM2007B', 'Producción y mercadotecnia audiovisual', 9),
    ('Producción y mercadotecnia audiovisual', 'TM3001B', 9),
    ('TM3001B', 'Proyecto integrador de tecnología y producción musical', 9),
    ('Proyecto integrador de tecnología y producción musical', 'P2001B', 9),
    ('P2001B', 'Opinión pública', 9),
    ('Opinión pública', 'P2002B', 9),
    ('P2002B', 'Instituciones, regulación y política pública', 9),
    ('Instituciones, regulación y política pública', 'TC2001B', 9),
    ('TC2001B', 'Ciencia de datos para la toma de decisiones I', 9),
    ('Ciencia de datos para la toma de decisiones I', 'TC3066', 9),
    ('TC3066', 'Métodos econométricos y política pública', 9),
    ('Métodos econométricos y política pública', 'EC2002B', 9),
    ('EC2002B', 'Economía conductual y neurociencia política', 9),
    ('Economía conductual y neurociencia política', 'P2003B', 9),
    ('P2003B', 'Políticas tecnológicas para el desarrollo', 9),
    ('Políticas tecnológicas para el desarrollo', 'P2013', 9),
    ('P2013', 'Elección pública e instituciones políticas comparadas', 9),
    ('Elección pública e instituciones políticas comparadas', 'TC2002B', 9),
    ('TC2002B', 'Ciencia de datos para la toma de decisiones II', 9),
    ('Ciencia de datos para la toma de decisiones II', 'EC3001B', 9),
    ('EC3001B', 'Análisis de decisiones bajo condiciones de incertidumbre', 9),
    ('Análisis de decisiones bajo condiciones de incertidumbre', 'P2020', 9),
    ('P2020', 'Economía política del cambio tecnológico y el desarrollo', 9),
    ('Economía política del cambio tecnológico y el desarrollo', 'P3001B', 9),
    ('P3001B', 'Gobierno, sector privado, tecnología y nuevos mercados', 9),
    ('Gobierno, sector privado, tecnología y nuevos mercados', 'TC3065', 9),
    ('TC3065', 'Experimentos e inferencia causal para política pública', 9),
    ('Experimentos e inferencia causal para política pública', 'P3002B', 9),
    ('P3002B', 'Diseño e implementación de innovaciones públicas', 9),
    ('Diseño e implementación de innovaciones públicas', 'AR1003B', 9),
    ('AR1003B', 'Modelación de la física en el ambiente construido', 9),
    ('Modelación de la física en el ambiente construido', 'CV1007', 9),
    ('CV1007', 'Razonamiento basado en matemáticas', 9),
    ('Razonamiento basado en matemáticas', 'CV1008', 9),
    ('CV1008', 'Resolución de problemas con lógica computacional', 9),
    ('Resolución de problemas con lógica computacional', 'AR1004B', 9),
    ('AR1004B', 'Modelación y representación gráfica de un edificio', 9),
    ('Modelación y representación gráfica de un edificio', 'AR1005B', 9),
    ('AR1005B', 'Modelación y representación gráfica de tu campus con topografía', 9),
    ('Modelación y representación gráfica de tu campus con topografía', 'AR1006B', 9),
    ('AR1006B', 'Modelación y representación gráfica de tu entorno con geomática', 9),
    ('Modelación y representación gráfica de tu entorno con geomática', 'CV1013', 9),
    ('CV1013', 'Análisis de fenómenos naturales y sociales con probabilidad y estadística', 9),
    ('Análisis de fenómenos naturales y sociales con probabilidad y estadística', 'AR2001B', 9),
    ('AR2001B', 'Diagnóstico territorial', 9),
    ('Diagnóstico territorial', 'AR2003B', 9),
    ('AR2003B', 'Ecobarrio', 9),
    ('Ecobarrio', 'AR2037', 9),
    ('AR2037', 'Derecho Urbano', 9),
    ('Derecho Urbano', 'BT2027', 9),
    ('BT2027', 'Ecología urbana', 9),
    ('Ecología urbana', 'CV2041', 9),
    ('CV2041', 'Infraestructura urbana', 9),
    ('Infraestructura urbana', 'AR2005B', 9),
    ('AR2005B', 'Ciudades competitivas: Innovación', 9),
    ('Ciudades competitivas: Innovación', 'AR2006B', 9),
    ('AR2006B', 'Ciudades competitivas: Movilidad', 9),
    ('Ciudades competitivas: Movilidad', 'AR2010B', 9),
    ('AR2010B', 'Ciudades competitivas: Calidad de vida', 9),
    ('Ciudades competitivas: Calidad de vida', 'AR2038', 9),
    ('AR2038', 'Ciudades del futuro', 9),
    ('Ciudades del futuro', 'AR3001B', 9),
    ('AR3001B', 'Metrópolis sostenible: Mitigación', 9),
    ('Metrópolis sostenible: Mitigación', 'AR3002B', 9),
    ('AR3002B', 'Metrópolis sostenible: Resiliencia', 9),
    ('Metrópolis sostenible: Resiliencia', 'AR3004B', 9),
    ('AR3004B', 'Metrópolis sostenible: Adaptación', 9),
    ('Metrópolis sostenible: Adaptación', 'EC2033', 9),
    ('EC2033', 'Economía urbana', 9),
    ('Economía urbana', 'AR3003B', 9),
    ('AR3003B', 'Gestión y administración de proyectos territoriales de inversión', 9),
    ('Gestión y administración de proyectos territoriales de inversión', 'AR3005B', 9),
    ('AR3005B', 'Ciudades emergentes', 9),
    ('Ciudades emergentes', 'AR3006B', 9),
    ('AR3006B', 'Complejidad y debate', 9);
